### ISSUE TITLE
[bug] Can't display full content - CSS Style

### ISSUE THREAD

**Issue by zsnmwy** [labring/laf#1003]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

https://laf.dev

### What happened

#  CSS Style
<img width="380" alt="image" src="https://user-images.githubusercontent.com/35299017/229662428-a61bd9f9-d3bf-4e89-9925-2973aeb12011.png">
<img width="946" alt="image" src="https://user-images.githubusercontent.com/35299017/229662523-ba919567-58b7-4ade-af79-6b446ca33f2f.png">

# Try to Fix It

Remove `overflow: hidden`
![image](https://user-images.githubusercontent.com/35299017/229662685-48c2739e-ecd6-491e-bd06-93775d86eac3.png)

# Have the same problem  in the Logs Detail

<img width="913" alt="image" src="https://user-images.githubusercontent.com/35299017/229663084-fabfdb2e-da69-439b-ad72-0c912feb2613.png">

# scope
- laf.dev
- self-host web

### How to reproduce

Return a large object in the code.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by yuedanlabs** [comment]
The latest version online has fix this bug.

Just refresh laf.dev or laf.run to check it.

**Comment by zsnmwy** [comment]
Do you know how about the self-host version?
Are the images updated?

**Comment by yuedanlabs** [comment]
the image has been updated just now (1 hour ago).

you can check it by your self.

<img width="470" alt="image" src="https://user-images.githubusercontent.com/95392548/231151416-4f8f3a1d-4d2b-4705-b427-d47361418e78.png">

**Comment by zsnmwy** [comment]
thanks😘

**Comment by zsnmwy** [comment]
# Try
I try to upgrade the image to their image version. And force refresh the page.

```shell
image: docker.io/lafyun/laf-server@sha256:48fe5b854b68fb141592e34665f8479da67ae3b91d2448436c4592c09ee3ba4d                                                                            

image: docker.io/lafyun/laf-web@sha256:02ed6d070a18e1fa4606ca444dcf8c4f9ffeb57cce6e10b1371d0220439d0858
```

<img width="1027" alt="image" src="https://user-images.githubusercontent.com/35299017/231160034-03b4b80b-5daa-4cbf-addd-a4a973678609.png">
<img width="822" alt="image" src="https://user-images.githubusercontent.com/35299017/231160079-d0cafa86-e1b7-4137-b3e6-7715f87266f3.png">

# Problem

But it still has the same problems.

<img width="1370" alt="image" src="https://user-images.githubusercontent.com/35299017/231161200-f295ceb5-31ff-4483-a134-3ef304f2052b.png">


**I need to disable the CSS style to fix it.**

<img width="1188" alt="image" src="https://user-images.githubusercontent.com/35299017/231161755-33d8b18f-fb26-4db7-b4c5-30b25f53fe90.png">

**Comment by maslow** [comment]
```sh
kubectl set image deployments/laf-server -n laf-system \
	laf-server=docker.io/lafyun/laf-server:sha-17676ea

kubectl set image deployments/laf-web -n laf-system \
	laf-web=docker.io/lafyun/laf-web:sha-7ad26a0
```

Run this in your master node.

**Comment by zsnmwy** [comment]
> ```shell
> kubectl set image deployments/laf-server -n laf-system \
> 	laf-server=docker.io/lafyun/laf-server:sha-17676ea
> 
> kubectl set image deployments/laf-web -n laf-system \
> 	laf-web=docker.io/lafyun/laf-web:sha-7ad26a0
> ```
> 
> Run this in your master node.

It's work. Thanks.

If possible add git hash to application env?
Std out the git hash when the application bootstrap.

If I use the latest image version, I can't know which git commit version was used.
