### ISSUE TITLE
How to replace the URL of official API of openAI in the example of setting up ChatGPT in three minutes?

### ISSUE THREAD

**Issue by Hokia** [labring/laf#1013]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Question

I guess like this:
export async function main(ctx: FunctionContext) {
  const { ChatGPTAPI } = await import('chatgpt')
  const url = 'https://api.myown.com/v1/chat/completions'
  const data = ctx.body

But I can not make sure it works.

**Comment by nightwhite** [comment]
Reference document：https://www.npmjs.com/package/chatgpt
