### ISSUE TITLE
[bug] Unable to query collection through mongo 

### ISSUE THREAD

**Issue by hankeke** [labring/laf#1041]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

https://laf.dev

### What happened

```js
import cloud from '@lafjs/cloud'
const mongo = cloud.mongo
export async function main(ctx: FunctionContext) {
  const collections = await mongo.db.collections()
  console.log('collections', collections)

  const list = mongo.db.listCollections()
  console.log('list', list)
}
```
#  cannot respond
1. await mongo.db.collections() 
2. mongo.db.listCollections() 

### How to reproduce

```js
import cloud from '@lafjs/cloud'
const mongo = cloud.mongo
export async function main(ctx: FunctionContext) {
  const collections = await mongo.db.collections()
  console.log('collections', collections)

  const list = mongo.db.listCollections()
  console.log('list', list)
}
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by shiwoaz** [comment]
hey, you can query collections by these ways.
```js
import cloud from '@lafjs/cloud'

export async function main(ctx: FunctionContext) {
  const m = cloud.mongo
  const list = m.db.listCollections()
  const collections_1 = await list.toArray()
  console.log(1, collections_1)

  const collections = await m.db.collections()
  collections.map(i => console.log(i.collectionName))
  return collections_1
}
```

you also can see the logs in log tab 

more information about mongo in cloud refer to [here](https://github.com/labring/laf/blob/main/packages/cloud-sdk/src/cloud.interface.ts#L58)

**Comment by hankeke** [comment]
thanks!
