### ISSUE TITLE
[bug] bug Laf 接入chatgpt 报错“fetch failed”

### ISSUE THREAD

**Issue by lbtcws** [labring/laf#1044]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

https://laf.dev

### What happened

RequestID: 8437f999-e75e-4af6-8ef0-59581727c10b 

[2023-04-18 08:23:53]
'fetch failed' 'TypeError: fetch failed\n' +
  '    at Object.fetch (node:internal/deps/undici/undici:11413:11)\n' +
  '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
  '    at async Promise.then.promptTokens (file:///app/node_modules/chatgpt/build/index.js:298:25)'

### How to reproduce

import cloud from ‘@lafjs/cloud’
export async function main(ctx: FunctionContext) {
const { ChatGPTAPI } = await import(‘chatgpt’)
const api = new ChatGPTAPI({ apiKey: cloud.env.CHAT_GPT_API_KEY })
let res = await api.sendMessage(‘“鸡你太美”指的是中国大陆哪位男艺人？给你个提示，他喜欢唱、跳、篮球、Rap’)
console.log(res)
return res.text
}

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by nightwhite** [comment]
let res = await api.sendMessage(‘“鸡你太美”指的是中国大陆哪位男艺人？给你个提示，他喜欢唱、跳、篮球、Rap’)

这里的引号是错的，要用英文引号

**Comment by feZsy** [comment]
改成这样还是不行呢
import cloud from '@lafjs/cloud'
export async function main(ctx: FunctionContext) {
  const { ChatGPTAPI } = await import('chatgpt')
  const api = new ChatGPTAPI({ apiKey: cloud.env.CHAT_GPT_API_KEY })
  let res = await api.sendMessage('鸡你太美')
  console.log(res)
  return res.text
}

**Comment by feZsy** [comment]
我改成这样还是不行
import cloud from '@lafjs/cloud'
export async function main(ctx: FunctionContext) {
  const { ChatGPTAPI } = await import('chatgpt')
  const api = new ChatGPTAPI({ apiKey: cloud.env.CHAT_GPT_API_KEY })
  let res = await api.sendMessage('鸡你太美')
  console.log(res)
  return res.text
}

**Comment by feZsy** [comment]
RequestID: f2ac692e-ced2-476a-96fb-39978d79a110 

[2023-04-18 08:36:34]
'fetch failed' 'TypeError: fetch failed\n' +
  '    at Object.fetch (node:internal/deps/undici/undici:11413:11)\n' +
  '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
  '    at async Promise.then.promptTokens (file:///app/node_modules/chatgpt/build/index.js:298:25)'

**Comment by feZsy** [comment]
![image](https://user-images.githubusercontent.com/27257365/232779922-46b5290c-af5f-4991-b5c3-751b08c4200a.png)

**Comment by feZsy** [comment]
> 你这个应用是国内的，访问不了 ChatGPT api 的。 请用： https://laf.dev

感谢，用你的方式解决了我的问题😄 

[https://laf.run/这个是国内的](https://laf.run/%E8%BF%99%E4%B8%AA%E6%98%AF%E5%9B%BD%E5%86%85%E7%9A%84)
[https://laf.dev/这个是国外服务](https://laf.dev/%E8%BF%99%E4%B8%AA%E6%98%AF%E5%9B%BD%E5%A4%96%E6%9C%8D%E5%8A%A1)

**Comment by AllenLuosong** [comment]
那么问题来了，我开发这个网站本来就是给国内用户使用的，现在我自己都要科学上网才能访问，那其他用户不也要这样才能访问吗？

**Comment by nightwhite** [comment]
可以看看这个：https://forum.laf.run/d/382
