### ISSUE TITLE
feat: impl command line tools in serverless-devs

### ISSUE THREAD

**Issue by maslow** [labring/laf#105]
1. impl cli component for laf in https://github.com/serverless-devs/serverless-devs
2. support: db collection export/import, sync functions, sync policies, oss bucket sync, tail function logs, invoke/debug functions.

init config file schema: 
```json
{
   "remote": "https://console.lafyun.com",
   "appid": "",
   "root": "@laf"
}
```

Commands:
- `login [-u username] [-p password]`
- `init <appid>`
- `fn pull [function-name] [-f, --force-overwrite]`
- `fn push [function-name] [-f, --force-overwrite]`
- `fn invoke <function-name> [--debug] `
- `fn publish [function-name] [--all]`
- `oss push <input-path> <bucket> [-f, --force-overwrite]`
- `oss pull <bucket> <out-path> [-f, --force-overwrite]`
- `list`
- `restart [appid]`
- `start [appid]`
- `stop [appid]`
- `db export <collection-name> <out-path>`
- `db import <input-file-path> <collection-name>`
- `logs [-f, --follow] [-n, --tail] [--until]`

**Comment by maslow** [comment]
由于 laf 的 api 接下来要进行全面重构，所以正式版的 cli 工作延迟到这次重构完成之后。

**Comment by maslow** [comment]
laf next 版本重构完成前，会再次评估 cli 的开发方式

**Comment by anycodes** [comment]
目前 Serverless devs 已经进入了 CNCF Sandbox，同时 OpenFunction 等也顺利接入了 Devs，欢迎 LAF 可以将 Devs 作为一个实现方案来做。

另外，Serverless Devs 本身拥有Registry和白屏应用中心方案，我相信，对LAF的一些规划是有助力加速的效果的。
