### ISSUE TITLE
[bug] Can function names support individual characters 

### ISSUE THREAD

**Issue by hankeke** [labring/laf#1053]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

https://laf.dev

### What happened

1. Can function names support single characters ？
![image](https://user-images.githubusercontent.com/11770232/233259890-2761bc14-f2b1-4ab8-a2c5-0b25152f3ef8.png)

### How to reproduce

1.Add a cloud function with a single character name
# eg: 
![image](https://user-images.githubusercontent.com/11770232/233260056-1fe096f4-2ceb-4016-a26c-75daec529c48.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by nightwhite** [comment]
not support

**Comment by maslow** [comment]
Could be support in next release
