### ISSUE TITLE
[Feature] will 1.0 Adding Index Management and Collection Structure？

### ISSUE THREAD

**Issue by juukee** [labring/laf#1078]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

will 1.0 Adding Index Management and Collection Structure？

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
Sure, we will add indexes management soon.
