### ISSUE TITLE
[bug] Deploy laf on rke, it happens white screen when visit dashboard

### ISSUE THREAD

**Issue by warjiang** [labring/laf#1080]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

Linux (self-host)

### What happened

after follow steps of https://github.com/labring/laf/blob/main/deploy/build/README.md, i have deploy laf in self hosted kubernets successfully. I can visit homepage of laf, but when i try to visit dashboard for more functions, it happens white screen, some errors happens in the dev console
![image](https://user-images.githubusercontent.com/6478745/234190663-00f6ea1c-27c2-4c61-b7ec-15efce7fc03d.png)
![image](https://user-images.githubusercontent.com/6478745/234190715-c522b16d-c2e0-4cdf-9696-b19befed1dbf.png)

i have try to fix the problems in subfolder named web dir:
i modify the file `laf/web/src/pages/home/mods/CreateAppModal/index.tsx`:
![image](https://user-images.githubusercontent.com/6478745/234190892-6be27c2b-3d2e-4c4e-902d-0857c30fb38d.png)

but more error occurs:
![image](https://user-images.githubusercontent.com/6478745/234191083-3a79cd1d-3586-4ace-879a-948712454458.png)

it seems that laf team suppot i18n, but i18n not fit for self hosted case;

### How to reproduce

install follow the steps described in https://github.com/labring/laf/blob/main/deploy/build/README.md

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
Fixed in latest version.

**Comment by warjiang** [comment]
> Fixed in latest version.

@maslow cannot found any commit in the latest release, https://github.com/labring/laf/releases/tag/v1.0.0-beta.10, not release yet?
