### ISSUE TITLE
[fix]  建议集合管理中对文档操作进行优化

### ISSUE THREAD

**Issue by hankeke** [labring/laf#109]
1.当文档中的某条记录数据很多时，编辑和删除按钮不容易找到，必须翻到该条记录的最上面才可以做相应的操作
2.建议可以悬浮在我要操作的地方
![image](https://user-images.githubusercontent.com/11770232/169574892-56893585-d5aa-4600-b15d-17fff3d56457.png)

**Comment by maslow** [comment]
我建议优化的方式：
每条文档记录，使用固定的高度（max-heigh）， 不然文档太长，不方便浏览和操作。
