### ISSUE TITLE
[bug] The default .gitignore file pulled by the command line tool (laf-cli) may be faulty

### ISSUE THREAD

**Issue by HUAHUAI23** [labring/laf#1140]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

https://laf.dev

### What happened

<img width="166" alt="image" src="https://github.com/labring/laf/assets/43649186/3053041a-2b01-428d-8109-b12bf0f8fb10">

It should be laf.yaml

### How to reproduce

1. `laf app init [appid]`
2. `cat  laf.yaml`

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by nightwhite** [comment]
#1136 

Waiting for new cli to be released
