### ISSUE TITLE
[Question]  How can i upgrade the Application Specification

### ISSUE THREAD

**Issue by zsnmwy** [labring/laf#1142]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Question

<img width="758" alt="image" src="https://github.com/labring/laf/assets/35299017/4e34c9dc-d711-4bd4-9dd7-3af9ce0b15fb">

I want to upgrade the existing application to 1c2g.

<img width="1303" alt="image" src="https://github.com/labring/laf/assets/35299017/9881ca08-9985-496d-a2d6-14ca656ab4ac">

**Comment by LeezQ** [comment]
upgrade Application Specification already published, now you can upgrade Specification by yourself.
<img width="729" alt="image" src="https://github.com/labring/laf/assets/972813/d6d76e5d-aea5-4991-a29f-021d11ad733e">
