### ISSUE TITLE
[bug] Is running a cloud function equivalent to publishing?

### ISSUE THREAD

**Issue by nightwhite** [labring/laf#1156]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

https://laf.dev

### What happened

Currently, I have modified the cloud function and clicked the run button to find that it has been published

### How to reproduce

1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
Not really.
