### ISSUE TITLE
[bug] Laf Application cannot be renamed

### ISSUE THREAD

**Issue by nightwhite** [labring/laf#1157]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

https://laf.dev

### What happened

Laf Application cannot be renamed

### How to reproduce

![image](https://github.com/labring/laf/assets/22722256/b85dd08e-be59-4f26-b080-83606761b8ab)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by LeezQ** [comment]
fixed
