### ISSUE TITLE
[Feature]  add Svelte template

### ISSUE THREAD

**Issue by SaraiQX** [labring/laf#1181]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

Hi Laf team,
Many thanks for this amazing work.
Svelte is one of the emerging frontend frameworks in recent years and is very popular esp. among international community.
Venture to suggest integration with Svelte and/or SvelteKIT.
https://svelte.dev/
Thank you!

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
More information about this?    Welcome to disccuss with svelte or PR!
