### ISSUE TITLE
[bug] function too large & AxiosError: Network Error

### ISSUE THREAD

**Issue by hankeke** [labring/laf#1196]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

https://laf.dev

### What happened

When the content of a function is too large, an error will be reported when executed
![image](https://github.com/labring/laf/assets/11770232/2066dbca-0c78-46de-b302-07c3bb8a93c2)

### How to reproduce

Function Content Big Error，AxiosError: Network Error

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
Fixed.
