### ISSUE TITLE
[bug] laf-cli invalid pat

### ISSUE THREAD

**Issue by hankeke** [labring/laf#1200]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

https://laf.run

### What happened

- laf-cli 报错：
![image](https://github.com/labring/laf/assets/11770232/128d46ac-9f15-42d4-92ad-7fcca35960de)
- 多次执行退出会报错，不友好
![image](https://github.com/labring/laf/assets/11770232/6ed1e3e8-2246-4977-8876-5cb892c0931c)

### How to reproduce

# 登陆原应用

```yaml
laf login [pat] -r https://api.laf.run
```

# 创建原应用目录为 `laf-resource`

```yaml
mkdir laf-resource
```

# 进入原应用并且初始化

```yaml
cd laf-resource && laf app init [appid]
```

# 拉取原应用的函数 & 策略

```yaml
laf func pull && laf policy pull
```

# 退出原应用

```yaml
laf logout
```

# 登陆目标应用

```yaml
laf login [pat] -r https://api.laf.run
```

# 创建目标应用为 `laf-target`

```yaml
mkdir laf-target
```

# 进入目标应用并且初始化

```yaml
cd laf-target && laf app init [appid]
```

# 拷贝原应用的函数&策略

```yaml
cp -R ../laf-resource/functions ./  && cp -R ../laf-resource/policies  ./
```

# 推送函数&策略到目标环境

```yaml
laf func push && laf policy push
```

# 退出目标应用

```yaml
laf logout
```

- 重复上面的操作步骤，laf-cli 报错：
![image](https://github.com/labring/laf/assets/11770232/128d46ac-9f15-42d4-92ad-7fcca35960de)
- 多次执行退出会报错，不友好
![image](https://github.com/labring/laf/assets/11770232/6ed1e3e8-2246-4977-8876-5cb892c0931c)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by skyoct** [comment]
The new version won't appear anymore
