### ISSUE TITLE
[Feature] CDN Support

### ISSUE THREAD

**Issue by juukee** [labring/laf#1212]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

we need cdn support

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
Sorry about that, we are looking for CDN provider to cooperate.   There are no concrete plans yet.
