### ISSUE TITLE
[Feature] Idea supports file skipping and automatic import

### ISSUE THREAD

**Issue by hankeke** [labring/laf#1213]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

https://laf.dev

### What happened

Idea does not support file skipping and automatic import

### How to reproduce

Idea supports file skipping and automatic import

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
Welcome to pr this feature.
