### ISSUE TITLE
[Feature] import error 

### ISSUE THREAD

**Issue by juukee** [labring/laf#1218]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

'require() of ES Module /app/node_modules/chatgpt/build/index.js from /app/dist/support/function-engine/cache.js not supported.\n' +
  'Instead change the require of index.js in /app/dist/support/function-engine/cache.js to a dynamic import() which is available in all CommonJS modules.' '/app/dist/support/function-engine/cache.js:77\n' +
  '        return require(module);\n

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by juukee** [comment]
@maslow when can we import es modules?

**Comment by maslow** [comment]
Use `import()` for ESM modules: 
`const chatgpt = await import('chatgpt')`
