### ISSUE TITLE
能提供一下docker容器映射吗

### ISSUE THREAD

**Issue by mayjack0312** [labring/laf#123]
我想让容器路径映射到本地
大佬方便给下程序具体路径吗
最好直接能-v所有的内容

**Comment by maslow** [comment]
我还没太明白你的需求， 你要的是这个吗：https://github.com/labring/laf/blob/main/docker-compose.yml
或者这里的本地 volume 目录信息， 缺少哪些你需要的？

**Comment by mayjack0312** [comment]
想要本地 volume 目录信息

**Comment by maslow** [comment]
https://github.com/labring/laf/blob/main/deploy/docker-compose/docker-compose.yml
这里有所有服务的 volume 信息，除 app-service 外。
app-service 代码挂到容器中的目录是 /app

**Comment by mayjack0312** [comment]
> https://github.com/labring/laf/blob/main/deploy/docker-compose/docker-compose.yml 这里有所有服务的 volume 信息，除 app-service 外。 app-service 代码挂到容器中的目录是 /app

谢谢大佬
