### ISSUE TITLE
[bug] bucket has website hosting enabled, please delete it first

### ISSUE THREAD

**Issue by NMTuan** [labring/laf#1243]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

https://laf.run

### What happened

 i will remove the bucket, system tell me “bucket has website hosting enabled, please delete it first ”

but the hosting is not enabled。

### How to reproduce

i don't know how to reproduce,
i have enabled hosting, and bind the domain, and disabled the hosting.

app id: xyvklh 
bucket name: xyvklh-test

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
Already handled, you can reopen this issue if there are further problems.
