### ISSUE TITLE
[bug] cli login error: unknown option '-r'

### ISSUE THREAD

**Issue by leason-wan** [labring/laf#1246]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

https://laf.dev

### What happened

default login is https://api.laf.run
but i use https://api.laf.dev.
run the command:
```bash
laf login [pat] -r https://api.laf.dev
```
result :
error: unknown option '-r'

now i workaround with 
laf login in https://api.laf.run -> add user with https://api.laf.dev -> switch user

### How to reproduce

laf login [pat] -r https://api.laf.dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by juukee** [comment]
laf-cli  The Laf cli version has been upgraded and requires a new method
默认登录 `laf.run`，如果要登录 `laf.dev` 或私有部署的 laf 或其他`laf.run`账号可通过 添加user：
```
laf user add dev -r https://laf.dev
laf user switch dev
laf login [pat]
```
laf -v  Confirm the version you are using
