### ISSUE TITLE
[Feature] cli pull func support restful api style

### ISSUE THREAD

**Issue by leason-wan** [labring/laf#1247]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

my func name: robot/add
```bash
laf func pull robot/add
```
result:
```bash
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Request failed with status code 404".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

err function: cli/api/function
```js
export async function functionControllerFindAll(appid: string, configParams: RequestParams = {}): Promise<any> {
  return request({
    url: `/v1/apps/${appid}/functions`,
    method: "GET",
    ...configParams,
  });
}
```
this pull function can be replace by POST or de/en code

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by leason-wan** [comment]
Maybe this err need catch, log a clear info

**Comment by skyoct** [comment]
@leason-wan  404 error new code has been caught

**Comment by vance-liu** [comment]
`
laf login xxx
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Request failed with status code 502".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v18.17.0
`

**Comment by skyoct** [comment]
#1431

**Comment by skyoct** [comment]
> ` laf login xxx node:internal/process/promises:288 triggerUncaughtException(err, true /* fromPromise */); ^
> 
> [UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Request failed with status code 502".] { code: 'ERR_UNHANDLED_REJECTION' }
> 
> Node.js v18.17.0 `

please check app status
