### ISSUE TITLE
[bug] Failed to add geographic data

### ISSUE THREAD

**Issue by juukee** [labring/laf#1258]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

https://laf.dev

### What happened

import cloud from '@lafjs/cloud'

const db = cloud.database()
export default async function (ctx: FunctionContext) {
 const r =  db.collection('stores').add({"location": {
    "type": "Point",
    "coordinates": [
      "104.030550",
      "30.698919"
    ]
  }})
  console.log(r)
  return r
}

### How to reproduce

1.Add to database
2.The console displays successfully, but the front-end database does not display

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by HUAHUAI23** [comment]
```js
import cloud from '@lafjs/cloud'

const db = cloud.database()
export default async function (ctx: FunctionContext) {
  const r = await db.collection('stores').add({
    "location": {
      "type": "Point",
      "coordinates": [
        "104.030550",
        "30.698919"
      ]
    }
  })
  console.log(r)
  return r
}
```
Databases, network operations, etc. are asynchronous, so use the await keyword.
