### ISSUE TITLE
静态托管能力与github联动

### ISSUE THREAD

**Issue by fanux** [labring/laf#129]
又重新体验了一下 vercel 的静态托管，体验实在是太好了，而且几乎是都在 vercel 上操作就行，后续更新也会自动触发网站的更新。

laf 的 roadmap 中也可以考虑增强这部分的能力，CLI 和 配置 AK 等操作对比上还是更繁琐了一些。

**Comment by object-kaz** [comment]
使用webhook也许会方便一些

**Comment by fanux** [comment]
vercel 是有webhook 的

**Comment by maslow** [comment]
在考虑等 `laf-cli` 实现完成后，将与 github 联动的能力，直接提升到 应用级别，静态托管 是应用 的一部分。
