### ISSUE TITLE
云函数非常不稳定,web端时常连接不上

### ISSUE THREAD

**Issue by Mickeygogo** [labring/laf#1293]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

https://laf.dev

### What happened

我用的是laf.dev，然后新的付费机制出来后，我会在使用的时候打开应用，不使用时关闭应用，昨晚还可以调用的函数，到第二天就一直报400
![image](https://github.com/labring/laf/assets/79964964/13ebb4aa-3615-481c-80fa-0c98704d73c1)
![image](https://github.com/labring/laf/assets/79964964/c1d42b86-d8ae-451b-a76d-aa4d04cf898f)
![image](https://github.com/labring/laf/assets/79964964/be876779-3e15-4b44-be48-23741f9cea61)

### How to reproduce

晚上关闭应用，早上开启应用后调用就一直失败

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
先前的 runtime 确实有些问题，已修复， 重启应用 可自动更新到最新版本。
