### ISSUE TITLE
提供一个快速开始的前端 demo 

### ISSUE THREAD

**Issue by maslow** [labring/laf#130]
https://docs.lafyun.com/guide/quick-start/#%E5%9C%A8%E5%89%8D%E7%AB%AF%E9%A1%B9%E7%9B%AE%E4%B8%AD%E4%BD%BF%E7%94%A8%E4%BA%91%E5%87%BD%E6%95%B0

提供一个 demo 仓库， 修改上面「快速开始」文档， 直接 git clone 便可以直接跑起来。

**Comment by qingyggg** [comment]
交给我啦

**Comment by maslow** [comment]
> 交给我啦

是否有进展？

**Comment by qingyggg** [comment]
react版本  https://github.com/qingyggg/laf-react-getting-start.git

**Comment by qingyggg** [comment]
vue 版本 https://github.com/qingyggg/laf-vue-getting-start.git

**Comment by qingyggg** [comment]
Vue bug已经修好
