### ISSUE TITLE
[bug] Interceptor cannot intercept websocket

### ISSUE THREAD

**Issue by juukee** [labring/laf#1313]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

https://laf.dev

### What happened

Interceptor cannot intercept websocket

### How to reproduce

Interceptor cannot intercept websocket

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by 0fatal** [comment]
This is not a bug, websockets are not supported at the moment.
