### ISSUE TITLE
[Feature] website need show recharge record

### ISSUE THREAD

**Issue by NMTuan** [labring/laf#1326]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

- [x] I think the website need show recharge record.
- [ ] And i hope to see the monthly bills

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
Got.

**Comment by 0fatal** [comment]
![截屏2023-07-20 上午11 19 07](https://github.com/labring/laf/assets/72899968/03843089-2393-443c-8581-00f54078f3d1)
![截屏2023-07-20 上午11 20 34](https://github.com/labring/laf/assets/72899968/f2debb69-549b-4af4-83da-682c7f6531db)
