### ISSUE TITLE
[Feature] Support install packages from private npm registry

### ISSUE THREAD

**Issue by bingtsingw** [labring/laf#1350]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

Support install packages from private npm registry

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by bingtsingw** [comment]
@maslow 我想到了另一个可能更好的方案, 不用在线上支持私有仓库, 而是在本地`function push`的时候支持编译/部分编译, 这样可以将私有仓库的package或者monorepo中的subpackage都打包编译进来再push.

不过这是一种**local first**的开发模式, `function pull`就没什么意义了, 因为是打包编译过后的代码, 在线上编辑器直接修改编译产物的场景应该也木有.

**Comment by maslow** [comment]
嗯，自定义 registry 还是要支持一下的

**Comment by bingtsingw** [comment]
可以全部都要!

我刚试了一下本地编译打包, 简单项目的是可行的, 更多的复杂场景还没实践.

demo仓库在这里: https://github.com/bingtsingw/laf-demo-bundle, 如果要自动化, 也还有一些细节要处理, 比如哪些package需要打包, 哪些package可以跳过使用平台的依赖管理

**Comment by HUAHUAI23** [comment]
目前会把云函数进行编译然后保存，所以需要增加一个支持，如果云函数是已经编译的，就直接保存，不进行二次编译

**Comment by bingtsingw** [comment]
> 目前会把云函数进行编译然后保存，所以需要增加一个支持，如果云函数是已经编译的，就直接保存，不进行二次编译
 
我测试demo已经成功了, 编译过后的mjs, laf是可以执行的.

**Comment by bingtsingw** [comment]
安全设计上应当默认用户代码全都有风险, 不管代码是来自npm官方源, 私有源, 还是用户自己上传.
所以系统本来就应该隔离所有用户代码的执行环境, 跟私有仓库似乎关系不大.

**Comment by fanux** [comment]
是的，已经隔离了，担心有漏网之鱼 @bingtsingw

**Comment by maslow** [comment]
@0fatal  评估一下这个方案？

> @maslow 我想到了另一个可能更好的方案, 不用在线上支持私有仓库, 而是在本地`function push`的时候支持编译/部分编译, 这样可以将私有仓库的package或者monorepo中的subpackage都打包编译进来再push.
> 
> 不过这是一种**local first**的开发模式, `function pull`就没什么意义了, 因为是打包编译过后的代码, 在线上编辑器直接修改编译产物的场景应该也木有.

**Comment by bingtsingw** [comment]
我以前写过一个demo template: https://github.com/laflabs/laf-template-bundle, 简单验证了下是可以成功.

不过我倒是不着急用, 感觉laf改进运行时支持多语言和框架之后, 可以有更多的方式去编译和部署.

**Comment by maslow** [comment]
有两种方法暂可用：
一、通过给应用添加环境变量，通过初始化命令来安装 private npm registry
```
NPM_INSTALL_FLAGS="--registry=https://registry.npmmirror.com && npm install private-package --registry=https://private.registry"
```

二、在本地直接打包应用所需的所有依赖
`tar -cf node_modules.tar  ./node_modules`
将这个 node_modules.tar 文件直接上传至应用云存储中 `{appid}-cloud-bin`  bucket 中，应用启动时会自动加载和使用该包中的依赖。

**Comment by maslow** [comment]
@bingtsingw
