### ISSUE TITLE
[bug] laf-cli dep push bug

### ISSUE THREAD

**Issue by Zing22** [labring/laf#1357]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

https://laf.run

## Desc
When using 'laf dep push', the new dependencies will not be installed on laf. But the `package.json` will be modified and the user-defined dependencies will be removed (for this example, there are `tencentcloud-sdk-nodejs` and `crypto-js`).

This `package.json` file is generated by `laf dep pull` from another Laf App.

## After pushing
<img width="983" alt="image" src="https://github.com/labring/laf/assets/8966971/baa331ea-d4fb-4d23-b96b-8f3a32a4a8ac">

## Not install on Laf
<img width="334" alt="image" src="https://github.com/labring/laf/assets/8966971/87ba7614-d847-4f1a-a849-12f33fdf6d17">

### How to reproduce

1. `git clone git@github.com:sysucats/zhongdamaopu.git`
2. `cd zhongdamaopu`
3. `laf login laf_xxx`
4. `laf dep push`
5. `git status` to see the change of `package.json`

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by skyoct** [comment]
@Zing22 laf dep command will push the dependencies in the laf.yaml file to the cloud and update the local dependencies

**Comment by Zing22** [comment]
got it, i will try later with laf.yaml file. @skyoct
