### ISSUE TITLE
[bug] onnxruntime-node code got error only on laf cloud function

### ISSUE THREAD

**Issue by Zing22** [labring/laf#1368]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

https://laf.run

### What happened

This code can get expected output on MacOS, nodejs v18. But got error on laf cloud function. please help.

```js
const ort = require('onnxruntime-node')

async function predict() {
  // const session = cloud.shared['modelSession'];

  // prepare inputs. a tensor need its corresponding TypedArray as data
  const dataA = Float32Array.from([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]);
  const tensorA = new ort.Tensor('float32', dataA, [3, 4]);

  console.log(tensorA);
}

export default async function (ctx: FunctionContext) {
  await predict();
}
```

### How to reproduce

1. create laf cloud func
2. copy the above code and paste
3. run the cloud func
4. get error output

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
Fixed in #1470
