### ISSUE TITLE
[bug] When the domain name is accessed with a port, it cannot be used

### ISSUE THREAD

**Issue by juukee** [labring/laf#1385]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

https://laf.dev

### What happened

https://[fire.juukee.cn/firewall](https://fire.juukee.cn/firewall)   Accessible
https://fire.juukee.cn:443   Accessible
https://fire.juukee.cn:443/firewall  Not accessible  --want support
When the domain name is accessed with a port, it cannot be used

### How to reproduce

When the domain name is accessed with a port, it cannot be used

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by 0fatal** [comment]
I tried to reproduce it and nothing happened. Unless you are using a non-80 or non-443 port, the cloud function only supports binding to ports 80 or 443

Also, deliberately adding port 443 to https like "https://fire.juukee.cn:443/firewall" doesn't make any sense
