### ISSUE TITLE
apisix-etcd pod CrashLoopBackOff

### ISSUE THREAD

**Issue by hi-sunshine** [labring/laf#1389]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

Mac (self-host)

### What happened

There are two instance of apisix-etcd pod had CrashLoopBackOff status after cluster deployed a few hours late.
 
<img width="1035" alt="image" src="https://github.com/labring/laf/assets/16054648/3d2f4d19-f722-47a6-afe9-7ab81a6f1744">

get some info with pod logs

<img width="1782" alt="image" src="https://github.com/labring/laf/assets/16054648/b4972047-f373-452a-aabf-51e0fb343628">

so，which reason caused this etcdserver been removed from the cluster, any mind can provide ?

### How to reproduce

just deploy with laf/deploy/install-on-mac.sh, and after few hours, apisix-pod crashed

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by 0fatal** [comment]
Is your `DOMAIN` correct?

**Comment by 0fatal** [comment]
Maybe trying to deploy again can fix this
