### ISSUE TITLE
[bug] Delete installed rely on will jump

### ISSUE THREAD

**Issue by nightwhite** [labring/laf#1390]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

https://laf.dev

### What happened

Delete installed rely on will jump

### How to reproduce

Delete installed rely on will jump, I don't think there should be should jump

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
It has been fixed in the latest version.
