### ISSUE TITLE
deploy：Problem executing script

### ISSUE THREAD

**Issue by wjlcode** [labring/laf#1399]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Question

There was a problem executing the script：
Error from server (ServiceUnavailable): error when retrieving current configuration of:
Resource: "storage.k8s.io/v1, Resource=storageclasses", GroupVersionKind: "storage.k8s.io/v1, Kind=StorageClass"
Name: "local-hostpath", Namespace: ""
from server for: "manifests/host-path-sc.yaml": apiserver is shutting down
Error: exit status 1
hardware configuration
cpu:j1900  Memory：6G

**Comment by 0fatal** [comment]
If you're deploying directly with k8s and not through sealos, you'll need to handle pv,pvc,sc on your own
