### ISSUE TITLE
[bug] The database has been updated, but the front-end does not display it

### ISSUE THREAD

**Issue by juukee** [labring/laf#1400]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

https://laf.dev

### What happened

update the database,but cant show in the  WEB IDE

### How to reproduce

![1689291301566](https://github.com/labring/laf/assets/28680837/ebb25d36-01d6-4adf-affc-af1e02336a93)
![1689291331700](https://github.com/labring/laf/assets/28680837/97934074-bece-4cfd-88b9-8bebcb74f862)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by 0fatal** [comment]
don't migrate functions by modifying "__functions__" collection directly

**Comment by juukee** [comment]
it look like function  cache errors
