### ISSUE TITLE
[bug] circular reference

### ISSUE THREAD

**Issue by juukee** [labring/laf#1407]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

https://laf.dev

### What happened

Circular references in cloud functions have no errors and are difficult to troubleshoot

### How to reproduce

1. how to fix it?
2. how to  easy to find Circular references ?

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by skyoct** [comment]
@juukee I will add detection to indicate circular dependencies.

**Comment by juukee** [comment]
when can we use it ? Urgent need, more and more functions

**Comment by skyoct** [comment]
> when can we use it ? Urgent need, more and more functions

waiting #1388 merge
