### ISSUE TITLE
[Feature] I hope there is an API for collection index

### ISSUE THREAD

**Issue by NMTuan** [labring/laf#1409]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

laf_curd needs to manage the collection indexes. However, both api.laf.run and laf-client-sdk currently do not support this feature.

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
Indexes Management will be supported in next month.

**Comment by maslow** [comment]
Index management is supported in version v1.0.0-beta.12.   
@see https://github.com/labring/laf/releases/tag/v1.0.0-beta.12
