### ISSUE TITLE
[bug] bug title Failed to add external dependency in the panel.

### ISSUE THREAD

**Issue by hewenwu19971** [labring/laf#1424]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

https://laf.dev

### What happened

Failed to add external dependency in the panel.

### How to reproduce

Failed to add external dependency in the panel

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by 0fatal** [comment]
could you provide more information? @hewenwu19971

**Comment by maslow** [comment]
Reopen this issue if you have more information to us
