### ISSUE TITLE
[bug] webhosting cutom domain `HTTP 500`

### ISSUE THREAD

**Issue by aFlyBird0** [labring/laf#1460]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

https://laf.run

### What happened

<img width="1440" alt="image" src="https://github.com/labring/laf/assets/36830265/ea136ff8-ca59-4838-8dcf-3eba0e124b14">

In addition: `blog2.aflybird.cn` is OK

### How to reproduce

1. Create a bucket and add custom doamin
2. (I'm not sure it can reproduce 100%)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
@HUAHUAI23

**Comment by 0fatal** [comment]
can not  reproduce
