### ISSUE TITLE
[bug] weird website hosting status

### ISSUE THREAD

**Issue by aFlyBird0** [labring/laf#1461]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

https://laf.run

### What happened

The status of website hosting stuck at `deleting`

<img width="1440" alt="image" src="https://github.com/labring/laf/assets/36830265/7e157f66-880b-400d-9e07-3f79f8c49ba1">

①The left arrow means website hosting enabled
②However，the right one show the website hosting has been deleted
③They are conflicted
![image](https://github.com/labring/laf/assets/36830265/746f2883-b476-4f33-89e9-b83fe5c0b1f3)

### How to reproduce

I'm not sure.

①Maybe: Disable website hosting first, then **immediately** enable website hosting.
②It may be due to me toggling website hosting while simultaneously using the API to upload files.

This doesn't seem to be a stable and reproducible situation. It appears to be a low-frequency but indeed existing edge case.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
Fixed in https://github.com/labring/laf/commit/38447799a8e854e6993e86b7caef44bb3122626a
