### ISSUE TITLE
[Question] How to deploy laf with a custom domain?

### ISSUE THREAD

**Issue by code4you2021** [labring/laf#1478]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Question

Hello,

I reviewed the documentation but couldn't successfully deploy it. It works fine when deployed using an IP address, but I encounter errors when deploying with a custom domain.

https://github.com/labring/laf/blob/main/deploy/README.md

```

cd deploy

# replace with your domain here.
# can't work, if use IP work fine.
export DOMAIN= laf.io

# install k8s cluster
sh install-on-linux.sh $DOMAIN
```

Could you provide more detailed documentation? The deployment instructions are too abstract, and I have no idea how to resolve issues when they arise.

Thanks.

**Comment by nightwhite** [comment]
Is domain name resolution correct？
