### ISSUE TITLE
[bug] Cloud storage cannot be added after reaching 100

### ISSUE THREAD

**Issue by gdfsdjj145** [labring/laf#1501]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

https://laf.run

### What happened

Cloud storage cannot be added after reaching 100

### How to reproduce

Cloud storage cannot be added after reaching 100

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by 0fatal** [comment]
you should upgrade your specfication for more cloud storage space

**Comment by gdfsdjj145** [comment]
No matter how the configuration is changed, it only has 100 pieces of data，I guess this is a bug

**Comment by newfish-cmyk** [comment]
Fixed in #1519
