### ISSUE TITLE
[bug] The editor is not working properly when updating data in some situations.

### ISSUE THREAD

**Issue by DaZiYuan** [labring/laf#1524]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

https://laf.run

### What happened 
The LAF editor is unable to save data when the data is created within a transaction.

### How to reproduce

```
  const client = cloud.mongo.client;
  const session = client.startSession({ causalConsistency: true });

  try {
    //开启事务
    session.startTransaction();
    // add user
    const insertUserRes = await cloud.mongo.db.collection("user-system-users").insertOne({
      email,
     pwd
    });
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by 0fatal** [comment]
```
const insertUserRes = await cloud.mongo.db.collection("user-system-users").insertOne({
      email,
     pwd
    }, {session: session});
 ```

**Comment by DaZiYuan** [comment]
https://github.com/labring/laf/assets/80653/5bca5116-fdde-4954-b405-9f31b6035c3f

通过事务插入的数据，在编辑器无法修改

**Comment by 0fatal** [comment]
> chrome_WrxKymi1sS.mp4 
> 通过事务插入的数据，在编辑器无法修改

插入部分有更具体的代码吗

**Comment by DaZiYuan** [comment]
> > chrome_WrxKymi1sS.mp4
> > 通过事务插入的数据，在编辑器无法修改
> 
> 插入部分有更具体的代码吗

```
  //执行mongodb事务
  const client = cloud.mongo.client;
  const session = client.startSession({ causalConsistency: true });

  //开启事务
  session.startTransaction();
  // add user
  const insertUserRes = await cloud.mongo.db.collection("user-system-users").insertOne({
    email,
  });
  session.commitTransaction();
```

之前群里确认过，这样插入的Id是ObjectId，不是字符串

**Comment by 0fatal** [comment]
> > > chrome_WrxKymi1sS.mp4
> > > 通过事务插入的数据，在编辑器无法修改
> > 
> > 
> > 插入部分有更具体的代码吗
> 
> ```
>   //执行mongodb事务
>   const client = cloud.mongo.client;
>   const session = client.startSession({ causalConsistency: true });
> 
>   //开启事务
>   session.startTransaction();
>   // add user
>   const insertUserRes = await cloud.mongo.db.collection("user-system-users").insertOne({
>     email,
>   });
>   session.commitTransaction();
> ```
> 
> 之前群里确认过，这样插入的Id是ObjectId，不是字符串

确保在代码无误的情况下再进行后续的测试：
目前的代码有下面的问题
1. 事务中插入数据时，需要指定会话 
``` 
// 注意第二个参数
const insertUserRes = await cloud.mongo.db.collection("user-system-users").insertOne({
    email,
  }, { session });
  
  await session.commitTransaction();
  ```
  
  2. 操作完成最好close掉session，session.close()

**Comment by DaZiYuan** [comment]
加了第二个参数，效果也一样，后台数据还是无法修改。

close方法是错的，我之前写了`    session.endSession();`


```'session.close is not a function' 'TypeError: session.close is not a function\n' +```

**Comment by 0fatal** [comment]
确实是个 bug，感谢反馈。暂时可以通过 cloud.database().add 添加数据

**Comment by DaZiYuan** [comment]
绕不过去了，这里业务逻辑必须用事务，只有等你们修复

**Comment by maslow** [comment]
就用 ObjectId 就好了， 只是不能在 web 页面 修改， 写云函数是可以正常操作的。

**Comment by DaZiYuan** [comment]
是不影响线上，但是要想改一下数据就得写代码

**Comment by maslow** [comment]
ObjectId 问题的修复，已经在计划内了
