### ISSUE TITLE
[Feature] support waf

### ISSUE THREAD

**Issue by skyoct** [labring/laf#1541]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

support waf

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
This can be configured by the user on their gateway (if their gateway supports WAF), and in the laf public cloud, WAF support will also be configured at the gateway layer. Due to cost considerations of WAF, it will not be activated for now.
