### ISSUE TITLE
[Feature] I hope the web IDE can maintain the code browsing position

### ISSUE THREAD

**Issue by xintianyou** [labring/laf#1567]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

When switching between multiple cloud function tabs in the web IDE, the scroll bar in the code area cannot remain in one position, but will automatically return to the top.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
Good suggestions.
