### ISSUE TITLE
请问是否有计划提供对sdk文件完整查看的功能, 目前按ctrl键只能查看一点点

### ISSUE THREAD

**Issue by cccy0** [labring/laf#159]

**Comment by maslow** [comment]
嗯，是要尽快安排，文档这块工作还需要大量工作，有没有兴趣一起贡献

**Comment by cccy0** [comment]
> 嗯，是要尽快安排，文档这块工作还需要大量工作，有没有兴趣一起贡献

如果有需要帮忙的地方乐意效劳 : )

**Comment by cccy0** [comment]
> 太需要了，需要什么帮助的话 可以约我在线沟通 或者 在这里也可以

我wx群里昵称就是cccy0, 有什么能帮的上忙的叫我就好😀
