### ISSUE TITLE
docker启动后, 访问8000没有页面

### ISSUE THREAD

**Issue by klren0312** [labring/laf#161]
是OpenResty的欢迎页
![image](https://user-images.githubusercontent.com/10903843/177685883-64f2b243-752c-4154-9c0a-a6138fe1bb52.png)

**Comment by maslow** [comment]
只能使用配置的域名访问，配置文件是同目录的 .env文件，如果没修改的话，就是部署文档上的访问域名，不支持通过 localhost访问

**Comment by jveay** [comment]
> 只能使用配置的域名访问，配置文件是同目录的 .env文件，如果没修改的话，就是部署文档上的访问域名，不支持通过 localhost访问

弱弱的问下大佬。这边如果是单独部署在云服务器上，使用自定义域名，解析都是解析到同一个ip么？还是说只是做一个泛解析到同一个ip就可以    如：*.domain.com
DEPLOY_DOMAIN=127-0-0-1.nip.io                     如：laf.domain.com
SYS_CLIENT_HOST=console.127-0-0-1.nip.io       如：console.domain.com
OSS_DOMAIN=oss.127-0-0-1.nip.io                     如：oss.domain.com

**Comment by klren0312** [comment]
> 只能使用配置的域名访问，配置文件是同目录的 .env文件，如果没修改的话，就是部署文档上的访问域名，不支持通过 localhost访问

收到

**Comment by SheepYang1993** [comment]
配置成这样，还是访问不了
DEPLOY_DOMAIN=testapi.com
SYS_CLIENT_HOST=console.testapi.com
OSS_DOMAIN=oss.testapi.com

**Comment by maslow** [comment]
> > 只能使用配置的域名访问，配置文件是同目录的 .env文件，如果没修改的话，就是部署文档上的访问域名，不支持通过 localhost访问
> 
> 弱弱的问下大佬。这边如果是单独部署在云服务器上，使用自定义域名，解析都是解析到同一个ip么？还是说只是做一个泛解析到同一个ip就可以 如：*.domain.com DEPLOY_DOMAIN=127-0-0-1.nip.io 如：laf.domain.com SYS_CLIENT_HOST=console.127-0-0-1.nip.io 如：console.domain.com OSS_DOMAIN=oss.127-0-0-1.nip.io 如：oss.domain.com

做泛解析 即可

**Comment by SheepYang1993** [comment]
已解决，在域名解析那边做泛解析
