### ISSUE TITLE
会有微信云开发的迁移工具或迁移指南吗？

### ISSUE THREAD

**Issue by aecra** [labring/laf#162]

**Comment by maslow** [comment]
正在准备这块工作，因为 laf 并不是微信云开发的 精确平替，有很多地方还是有差异的，迁移会有障碍，我也正在调研这块

**Comment by kingwangim** [comment]
期待 👀

**Comment by yenche123** [comment]
@aecra @kingwangim 我写的 https://github.com/yenche123/all-serverless
看能不能帮助到你们
