### ISSUE TITLE
[bug] Time display error

### ISSUE THREAD

**Issue by mrchenxxx** [labring/laf#1698]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

https://laf.dev

### What happened

The front-end display is not the same as the log time display, the front-end display is wrong

### How to reproduce

console.log(new Date())
![image](https://github.com/labring/laf/assets/44868578/2ea00c2e-0c70-4b88-88cb-ebfb05ad184b)
![image](https://github.com/labring/laf/assets/44868578/05cd4e8f-8bbb-47cd-8f81-4e7369540006)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
This time display is correct and as expected. One shows the time in the client's time zone, and the other prints the timestamp.
