### ISSUE TITLE
本地搭建，但是端口已经被其他项目占用了80和443端口，想指定laf端口，比如888

### ISSUE THREAD

**Issue by hgc357341051** [labring/laf#1715]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

本地搭建，但是端口已经被其他项目占用了80和443端口，想指定laf端口，比如888，一键部署的也加上端口参数，谢谢

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by hgc357341051** [comment]
可以先不考虑增加SSL证书，本地测试

**Comment by maslow** [comment]
需要自行修改  nginx ingress 的 deamonset 中的端口号， 改成其它的端口。 同时， 修改数据库中 sys_db.Region.gatewayConf.port 端口号配置
