### ISSUE TITLE
私有部署能否关闭注册功能

### ISSUE THREAD

**Issue by jxzhn** [labring/laf#172]
目前好像没有这项功能，那不是任何人都可以打开你的控制台注册一个账号并使用了吗🥲

**Comment by maslow** [comment]
是的，暂时是没有这个功能，需要做一个配置 控制注册。 

现在可以通过 system-server 的一个配置来控制用户可创建的应用数量： ACCOUNT_DEFAULT_APP_QUOTA

比如将 ACCOUNT_DEFAULT_APP_QUOTA 设为0， 默认 注册的用户，将没有创建应用的额度。

**Comment by maslow** [comment]
已支持，待下次发版
