### ISSUE TITLE
关于默认gateway容器中的resolver配置

### ISSUE THREAD

**Issue by i-moxi** [labring/laf#173]
我使用的容器平台是 podman 并安装了 dnsname，其在创建bridge网卡后默认并没有使用和Docker相同的 127.0.0.11 作为DNS Server。
其会造成如下现象：
1. 可以加载登录界面，但无法正常登录
2. 少数情况可以正常登录，可以创建环境和修改函数，无法调试或者触发器访问，且观察到 log 出现大量 HTTP 111
3. 白屏无法加载后台界面

解决方法：
修改 packages/gateway 里面三个文件的 resolver 值为
`resolver local=on;
`
修改compose.yml里面gateway的image，使其指向本地
`  gateway:
    build: ../../packages/gateway
    depends_on:
`
似乎大家都是用docker或者k8s部署的，没有看到相关的bug记录，在这里留一个解决方式节约后来人的时间。
由于我缺少环境测试 local=on 之后是否会影响其他平台的用户，故不提交pr留个issue记录一下

**Comment by maslow** [comment]
感谢 @i-moxi 反馈和解决方案，我将这个 issue 收集到 QA 中去了：https://github.com/labring/laf/discussions/174
