### ISSUE TITLE
[Feature] Better readability of function names in func head panel

### ISSUE THREAD

**Issue by sulnong** [labring/laf#1760]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

If you have many cloud functions, a common way  to organize and manage them is through directories, and LAF also provides us with this approach. 
Now on func name panel, what it display is `full function path` instead of `function real name`,  see below

![for-issue](https://github.com/labring/laf/assets/37979965/6d099604-5407-4680-b337-949656135a3d)

### In vscode, it looks like this(only filename, not full file path), see below
![issue](https://github.com/labring/laf/assets/37979965/60b9aa25-4197-4ddd-98b0-332e38c87853)

I like func name displayed in vscode style, and this just an advice, pr at #1759  

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by 0fatal** [comment]
#1759
