### ISSUE TITLE
[Question] About commit (#1766)  What was the reason for removing  AddRulesModal button and AddPolicyModal button, how to add policy and rules

### ISSUE THREAD

**Issue by zqqq** [labring/laf#1789]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Question

After this commit (#1766) in the file web/src/pages/app/database/PolicyListPanel/index.tsx, the following changes were made:

The data is now displayed based on the condition policyList?.data?.length === 0. If policyList?.data?.length is 0, the PolicyListPanel will not be shown. In this case, how can we add a new policy if the PolicyListPanel is not displayed?
Even if the PolicyListPanel is displayed, the button for AddPolicyModal has been removed. Why was the AddPolicyModal button removed?
Similarly, in the file laf/web/src/pages/app/database/PolicyDataList/index.tsx, the button for AddRulesModal has also been removed. What was the reason for removing this button?

**Comment by 0fatal** [comment]
we want to deprecate this feature in the future. We can completely implement it by writing cloud functions and even get better security.
