### ISSUE TITLE
[bug] Error occurs when deploying laf without using sealos-cloud.

### ISSUE THREAD

**Issue by jveay** [labring/laf#1808]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

Linux (self-host)

### What happened

Error: INSTALLATION FAILED: expected at most two arguments, unexpected arguments: Cluster\\nmetadata:\\n, finalizers:\\n, -, cluster.kubeblocks.io/finalizer\\n, labels:\\n, clusterdefinition.kubeblocks.io/name:, mongodb\\n, clusterversion.kubeblocks.io/name:, mongodb-5.0\\n, sealos-db-provider-cr:, <%-, name, %>\\n, annotations:, {}\\n, name:, <%-, name, %>\\n, namespace:, laf-system\\nspec:\\n, affinity:\\n, nodeLabels:, {}\\n, podAntiAffinity:, Preferred\\n, tenancy:, SharedNode\\n, topologyKeys:, []\\n, clusterDefinitionRef:, mongodb\\n, clusterVersionRef:, mongodb-5.0\\n, componentSpecs:\\n, -, componentDefRef:, mongodb\\n, monitor:, true\\n, name:, mongodb\\n, replicas:, <%-, replicas, %>\\n, resources:\\n, limits:\\n, cpu:, <%-, limitCPU, %>m\\n, memory:, <%-, limitMemory, %>Mi\\n, requests:\\n, cpu:, <%-, requestCPU, %>m\\n, memory:, <%-, requestMemory, %>Mi\\n, serviceAccountName:, laf-mongodb-<%-, name, %>\\n, volumeClaimTemplates:\\n, -, name:, data\\n, spec:\\n, accessModes:\\n, -, ReadWriteOnce\\n, resources:\\n, requests:\\n, storage:, <%-, capacity, %>Mi\\n, terminationPolicy:, Delete\\n, tolerations:, []\\n\""}, ./charts/laf-server

### How to reproduce

An error occurred when deploying using the path /build/start.sh script.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jveay** [comment]
I have already fixed this issue in this pull request. #1810  However, there is a problem with the application not being able to start after deployment. The laf-server log shows the following error
![image](https://github.com/labring/laf/assets/21017524/19726f63-e4fe-4eeb-824c-99540ba56e7d)

**Comment by maslow** [comment]
@HUAHUAI23   @0fatal
