### ISSUE TITLE
Install Fail sealos not installed

### ISSUE THREAD

**Issue by Laurel-rao** [labring/laf#1815]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

https://laf.dev

### What happened

`run install_on_linux`
```
No package sealos=4.3.5 available.
Error: Nothing to do
...
ARCH: amd64
sealos not installed
```

update the version to 4.3.7 will be ok.

### How to reproduce

edit the shell ,change version from 4.3.5 to 4.3.7 will be fine

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by 0fatal** [comment]
close for #1816 

thanks for your contribution!
