### ISSUE TITLE
uniapp开发小程序，用客户端 SDK 的访问数据库报错

### ISSUE THREAD

**Issue by qzgang** [labring/laf#183]
### 开发环境
1、HBuilder X版本 3.4.18.20220630 
2、微信开发工具版本 1.06.2206271 RC
3、laf-client-sdk版本
```
"laf-client-sdk": {
      "version": "0.8.2",
      "resolved": "https://registry.npmmirror.com/laf-client-sdk/-/laf-client-sdk-0.8.2.tgz",
      "integrity": "sha512-qQiz9uvdWKt4KKj/YPRW84BYYB6CeJtCcAiV+OZL1HQeMauQ/dG17MksN85TQXa9k8rO+EZ6ACisfmDrZ6sWGw==",
      "requires": {
        "axios": "^0.21.1",
        "database-ql": "^0.8.2"
      }
    }
```
### 问题描述
 运行环境设置为 `environment: "uniapp"`，访问数据库get()方法报错，当我把： `environment: "wxmp"`就好了。下图为错误情况的截图。
- 请求代码
<img width="674" alt="image" src="https://user-images.githubusercontent.com/13726548/178508887-25d0e36a-dc4f-49d3-a005-32d59a740f50.png">

- NetWork请求正常
<img width="617" alt="image" src="https://user-images.githubusercontent.com/13726548/178509498-64499888-c7c6-433f-a06a-f15ea70151f1.png">

- 错误信息
<img width="798" alt="image" src="https://user-images.githubusercontent.com/13726548/178509188-698fcc40-9ebd-4000-8b7b-e36c90f4c7f8.png">

**Comment by maslow** [comment]
update client sdk: `npm i af-client-sdk@0.8.12`
