### ISSUE TITLE
[bug] When using a non-80 or 443 port, there is an error in obtaining the file URL for the storage bucket.

### ISSUE THREAD

**Issue by jveay** [labring/laf#1831]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

Linux (self-host)

### What happened

![image](https://github.com/labring/laf/assets/21017524/fba98a0b-d9b9-41bd-966a-c39a5628a31a)

The correct URL should not have a port number after the bucket.

### How to reproduce

1/Use non-80 or 443 ports.
2/Upload file.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by 0fatal** [comment]
the same as #1830

**Comment by jveay** [comment]
@0fatal Pay attention to the URL in the screenshot, where the port appears twice. This indicates that the configuration stored in the database has been modified. It is a front-end bug.
