### ISSUE TITLE
有没有可能添加对traefik的支持

### ISSUE THREAD

**Issue by Jike0628** [labring/laf#193]
traefik 可以对容器内项目的访问 和自动申请ssl证书，感觉和当前项目很契合

**Comment by maslow** [comment]
好想法，@skyoct 正在实现基于 apisix 的 gateway，此次实现将 gateway 与 laf sys 解耦，是可以支持扩展 各种 gateway 的，traefik 会是一个很好的选择，未来可扩展支持
