### ISSUE TITLE
无法创建访问策略，页面上没有创建访问策略的按钮 Unable to create access policy, there is no button to create access policy on the page.

### ISSUE THREAD

**Issue by ShangyiAlone** [labring/laf#1938]
### Search before asking

- [ ] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

https://laf.dev

### What happened

![image](https://github.com/labring/laf/assets/92379749/42c7a018-d74d-47fe-a495-c0c84c69fb69)
Unable to create access policy, there is no button to create access policy on the page.

### How to reproduce

无法创建访问策略，Unable to create access policy,help

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
访问策略功能已经弃用， 只保留对过往应用的兼容。

**Comment by ShangyiAlone** [comment]
> 访问策略功能已经弃用， 只保留对过往应用的兼容。

那请问如何才能添加访问策略呢？

**Comment by ShangyiAlone** [comment]
> > 访问策略功能已经弃用， 只保留对过往应用的兼容。
> 
> 那请问如何才能添加访问策略呢？

是只能写爬虫么？我看了下那个请求头也不是很难构造，但是感觉这样很麻烦

**Comment by maslow** [comment]
已安排前端修复这个问题， 修复好会第一时间发版

**Comment by ShangyiAlone** [comment]
> 已安排前端修复这个问题， 修复好会第一时间发版

好的，感谢

**Comment by ShangyiAlone** [comment]
我编写了访问集合的脚本，有需要的小伙伴可以直接拿来用 
i write a script to get data from my set. use it if you need,i use ts

这里是链接（link）：https://github.com/ShangyiAlone/laf_script.git

```
import fetch, { Response } from 'node-fetch';

# 填入你请求的集合的网络路径
const url = 'https://laf.run/v1/apps/yours/databases/proxy';

const payload = {
    collectionName: 'cat',
    query: {},
    limit: 10,
    action: "database.queryDocument"
};

const headers = {
    'Content-Type': 'application/json',
    'Authorization': 'your authorization'
};

export function getCats() {
    return fetch(url, {
        method: 'POST',
        headers: headers,
        body: JSON.stringify(payload)
    })
    .then(response => response.json())
    .then(data => {
        const cats = data.data.list
        const catName : { [key: string]: any} = {}
        for (const cat of cats){
            // console.log(cat)
            catName[cat._id] = cat.nickname
        }
        return catName
    })
    .catch(error => {
        console.error('Error:', error);
    });
}
```
