### ISSUE TITLE
静态网站托管，能不能支持一下，直接在创建网站下，上传html/js/css/图片等静态资源

### ISSUE THREAD

**Issue by QinQuLiang** [labring/laf#194]
![jt](https://user-images.githubusercontent.com/50478918/179723730-a46272cf-3d68-42b8-91f2-c82cabaa9458.png)

**Comment by maslow** [comment]
当前网站托管的逻辑是， 基于 一个 云存储 bucket 创建网站托管，你直接新建一个 bucket 将 html/js/css 文件上传， 然后在 网站托管这里 选择此 bucket 配置 域名。

**Comment by orangelckc** [comment]
> 当前网站托管的逻辑是， 基于 一个 云存储 bucket 创建网站托管，你直接新建一个 bucket 将 html/js/css 文件上传， 然后在 网站托管这里 选择此 bucket 配置 域名。

注意：新建的桶需要公共读的权限！

另外，访问网站链接的时候需要手动的在地址栏添加/index.html，不知道是不是他们忘记给nginx配置入口文件了

**Comment by cooper1x** [comment]
我发现静态网站托管只能通过xxx.com/index.html访问，xxx.com/i就不支持了……

**Comment by maslow** [comment]
> 我发现静态网站托管只能通过xxx.com/index.html访问，xxx.com/i就不支持了……

是有这个问题，下周发布新版本，就能支持了
