### ISSUE TITLE
云函数禁用了还是可以进行访问

### ISSUE THREAD

**Issue by iarjian** [labring/laf#200]
1.云函数禁用时还是可以进行访问
2.禁用后删除云函数依然可以进行访问
3.删除掉之后添加同名云函数无法进行覆盖,请求结果还是之前的返回内容

**Comment by maslow** [comment]
新函数是否发布了？

**Comment by iarjian** [comment]
> 新函数是否发布了所有变更，都需要手动发布生效，包括禁止

看了下禁用函数重新发布就访问不了, 但是禁用之后不需要点击发布直接就可以进行删除, 然后删除了就存在上面说的第2,3条的问题, 相当于第2,3条必需要在1操作发布之后进行删除才不会有问题

**Comment by maslow** [comment]
明白了，这中间确实有问题

**Comment by yenche123** [comment]
我也遇到了，我在玩 WebSocket，很纳闷前端怎么指定连接（触发）到哪个云函数的，就再新建了一个云函数，同时也配置了 WebSocket:message / WebSocket:connection / WebSocket:close 等触发器，结果发现怎样都连不到第二个创建的云函数

**Comment by maslow** [comment]
当前正在进行的 laf next 版会重构和简化 函数发布流程，此问题在下一版本处理。
