### ISSUE TITLE
将新版 laf web 替换掉 system client

### ISSUE THREAD

**Issue by maslow** [labring/laf#204]
**任务背景**

当前的客户端分为两个项目，分别是 system-client 和 app-console。

这两个是用 vue2 js 实现的，实现的也比较粗糙。

新实现了 laf web 项目，计划合并且用vue3 ts vite 重构 system-client 和 app-console 这两个旧客户端。

现阶段先完成第一个目标，用 laf web 先替代掉 system-client 并发版。

完成这个目标后，再继续迁移 app console 进来。

**任务说明**

1. 测试 laf web 对标 system client 的功能
2. 补充实现 应用列表页面中 应用状态的轮训
3. laf web 当前开发分支是 feat-web
4. 实现应用跳转 app-console 

q: 新版去除 「开发」 按钮后， 入口不明显， 与原来文档 描述也就不一致了，再考虑一下 增加此按钮？

**Comment by Dunqing** [comment]
> 新实现了 laf web 项目，计划合并且用vue3 ts vite 重构 system-client 和 app-console 这两个旧客户端。

可以参与吗？

**Comment by maslow** [comment]
当然，这块是 @LeezQ 负责，你们沟通？

**Comment by LeezQ** [comment]
> > 新实现了 laf web 项目，计划合并且用vue3 ts vite 重构 system-client 和 app-console 这两个旧客户端。
> 
> 
> 
> 可以参与吗？

非常欢迎，我先列下任务列表，到时候可以认领任务参与

**Comment by Dunqing** [comment]
> 非常欢迎，我先列下任务列表，到时候可以认领任务参与

好的👌
