### ISSUE TITLE
docker-compose 部署后访问服务器 502

### ISSUE THREAD

**Issue by kingwangim** [labring/laf#221]
服务器使用 docker-compose 部署后，通过 IP 访问报502，除了 .env 下修改
<img width="396" alt="image" src="https://user-images.githubusercontent.com/87178664/182570830-d82f5b3d-403c-4e58-9592-8c02d9154d18.png">
三个地址替换成服务器 ip 外，请问还有其他需要修改的吗

**Comment by maslow** [comment]
换好后， 需要重启
