### ISSUE TITLE
[docker部署问题]ADD failed: file not found in build context or excluded by .dockerignore

### ISSUE THREAD

**Issue by doramart** [labring/laf#223]
如图所示，有哪位大佬遇到过，帮忙解答下，谢谢！：
![image](https://user-images.githubusercontent.com/11911066/182656217-5d5d5445-c723-443b-baee-0e89f8f49dd1.png)

**Comment by maslow** [comment]
这是按照什么步骤部署 出现的

**Comment by maslow** [comment]
你是要 运行 开发环境 是吗， 看错误信息是 npm run build 没成功。

**Comment by doramart** [comment]
我是准备部署生产环境，在 deploy 目录下进行的（/deploy/docker-compose）
操作环境：
Linux DoraNas 4.4.180+ #42218 SMP Mon Oct 18 19:16:55 CST 2021 x86_64 GNU/Linux synology_geminilake_720+
操作步骤：
git clone https://github.com/labring/laf.git
cd laf/deploy/docker-compose
修改配置文件：
.env，  /deploy/docker-compose/docker-compose.yml
主要修改了 mongodb 默认端口号27017（因为我的docker上有另外一个mongodb）以及 console.127-0-0-1.nip.io 配置了我自己的域名
依次执行：

docker network create laf_shared_network --driver bridge || true
docker pull lafyun/app-service:latest
最后一步执行报的以上截图的错误，docker我不是很熟，所以暂时没看出来是哪里的问题
docker-compose up

**Comment by skyoct** [comment]
@doramart docker-compose up 是在laf/deploy/docker-compose目录下执行的吗

**Comment by maslow** [comment]
看图中显示，你执行的目录并不对，你仔细看下，中间的指令，运^_^运行 up 的时候
