### ISSUE TITLE
大佬，这里有几个问题和建议，望关注，谢谢！

### ISSUE THREAD

**Issue by djun** [labring/laf#224]
【问题】
1，通过deploy docker-compose部署的私有化服务，从原来旧版本升级上来的，创建应用很慢、转半天（是我服务器问题吗？），而创建后点击”释放“应用提示成功但实际没有删除应用，日志也没有任何报错信息、只有常规的log内容
2，使用laf-cli时提示”Error: Cannot find module 'node:fs'“，我的操作是laf login到自己部署的私有化服务，但看报错看起来像是laf-cli本身的问题

【建议】
1，支持在界面上修改应用容量类型选项，而不是在MongoDB里手改（可能需要限制管理员才能修改）
2，容量选项，希望支持”不限容量“，比如内存填0则不限内存，同理数据库填0则不限数据库、存储填0则不限存储总容量（这在实际项目中非常有用，像存储这样的希望不限总容量是非常需要的，laf能优化的话就不用再单独部署一个对象存储了）

非常感谢！！

**Comment by djun** [comment]
大佬 时隔一周了，再补充一个问题哈：

**Comment by maslow** [comment]
> 【问题】 1，通过deploy docker-compose部署的私有化服务，从原来旧版本升级上来的，创建应用很慢、转半天（是我服务器问题吗？），而创建后点击”释放“应用提示成功但实际没有删除应用，日志也没有任何报错信息、只有常规的log内容 2，使用laf-cli时提示”Error: Cannot find module 'node:fs'“，我的操作是laf login到自己部署的私有化服务，但看报错看起来像是laf-cli本身的问题

你这个升级的问题挺特殊，可能需要更多信息，或者我现场看一下。 
laf-cli 报错是哪个指令的错误，也需要更多信息。 

或在微信上，直接沟通。

> 【建议】 1，支持在界面上修改应用容量类型选项，而不是在MongoDB里手改（可能需要限制管理员才能修改） 2，容量选项，希望支持”不限容量“，比如内存填0则不限内存，同理数据库填0则不限数据库、存储填0则不限存储总容量（这在实际项目中非常有用，像存储这样的希望不限总容量是非常需要的，laf能优化的话就不用再单独部署一个对象存储了）


这些建议挺好的，当前还没做到这一步，后面会逐步完善的。

**Comment by maslow** [comment]
> 大佬 时隔一周了，再补充一个问题哈：
> 
> 如何通过应用id 在别的语言程序下访问对应应用的云数据库（mongodb）和云存储（minio）？

云存储，可以通过生成一个 Service Account 提供给外部的应用访问， 在云存储界面上 有个 生成服务账户的按钮， 通过 标准的 S3 api 就可以操作。 

云数据库的话， 当前是没有开放外网访问的。 如果你的应用服务 和 laf 数据库是内网的话， 可以直接通过内网去访问: 

在云函数中 `console.log(cloud.env）应该能看到 数据库的连接信息。
