### ISSUE TITLE
云存储-文件管理的几个问题

### ISSUE THREAD

**Issue by summercn** [labring/laf#227]
【问题】

1. 删除已有的 bucket，会发送请求到 https://console.lafyun.com/sys-api/apps/${appId}/oss/buckets/oss ，出现网络超时，复现概率较高
2. 新建空 bucket 之后，点击到这个 bucket ，无法正常使用，长期处于 loading 状态，见下图。原因为 https://oss.lafyun.com/${appId-ossid}?delimiter=%2F&max-keys=100&prefix=%2F 接口超时（这个切换到小飞机使用全局网络翻墙之后，暂时解决）
3. 新建文件夹之后，如果不在这个文件夹上传任何文件，不会显示这个已经建立的文件夹（这个只是交互问题，可以忽略，顺便一提）

<img width="762" alt="image" src="https://user-images.githubusercontent.com/12590759/182852859-91b3fb2e-08f2-49d9-95ba-fb7b5ae05955.png">

**Comment by maslow** [comment]
我来复现一下

**Comment by maslow** [comment]
没能复现，可能是那段时间 服务器资源紧张导致的时延
