### ISSUE TITLE
PayloadTooLargeError

### ISSUE THREAD

**Issue by yinzhidong** [labring/laf#234]
When I send a post request,and the json payload is a little big(463kb),then the server response error is as follows.
Is it possible for developers to config the size of post payload themselves? 
Thanks!

![image](https://user-images.githubusercontent.com/22864444/183416384-a40662dd-7115-43d0-ad26-98a3f1dd011e.png)

**Comment by maslow** [comment]
got.  I'll reproduce & fix it soon

**Comment by yinzhidong** [comment]
> got. I'll reproduce & fix it soon

This is my pleasure
