### ISSUE TITLE
调试面板应当持久化显示在右边

### ISSUE THREAD

**Issue by moonrailgun** [labring/laf#235]
这个应该是一个非常高频操作。使用drawer的表现形式非常影响用户体验

**Comment by maslow** [comment]
ok, 我来考虑一下，看看空间是否充足，或者 可手动控制 隐藏 或 显示， 有兴趣 可以参与 改造一下？

**Comment by moonrailgun** [comment]
没问题。感觉上laf是一个非常有潜力的项目，但是前端交互做的尚不完善
