### ISSUE TITLE
关于 laf 集成 casdoor/OIDC 的讨论

### ISSUE THREAD

**Issue by maslow** [labring/laf#252]
https://casdoor.org/zh/

laf 计划集成 casdoor 以获得专业的 auth 方案：
a. auth 相关部分工作量大，集成 casdoor 后不必分心实现 auth；
b. casdoor 是可配置的，用户可按需方便的配置丰富的 auth 方式：手机、邮箱、微信、支付宝、github、google 等数十种；
c. laf 当前只有最简单的密码登陆，且缺失找回密码、修改密码、手机号邮箱验证等功能，集成 casdoor 直接可获得这些能力；
_d. 未来或可以考虑，开放 casdoor 能力给 laf 应用_

TRADE OFF：
1. 直接集成 casdoor，还是对 OIDC 做支持
2. 是否保留 laf 内置的密码登陆方式，还是直接使用 casdoor 提供的全能力
3. 怎样迁移旧有用户到 casdoor，尤其是没有明文密码的用户（以手机号为准、可使用验证码登陆或重置密码）
4. casdoor 的数据库选择，使用 sqlite 还是 postgresql 或 mysql（建议是 pg）

**Comment by zzjin** [comment]
我倾向于简单的OIDC支持

对于lafyun,可以独立的启动一套casdoor的服务(或者复用login.sealos.io),作为一个application的oauthprovider集成进去
<small>*目前cloud的auth本身就是一个casdoor的application,注册到cloud集群内运行的casdoor服务上*</small>

> 2\. 是否保留 laf 内置的密码登陆方式，还是直接使用 casdoor 提供的全能力

如果只支持OIDC,可以只提供一个脚本一键生成一个 token , 类似 `kubeadm token create`

> 3\. 怎样迁移旧有用户到 casdoor ，尤其是没有明文密码的用户（以手机号为准、可使用验证码登陆或重置密码）

可以把现有的数据库数据,复用一个现有的验证码登录页面,打包成一个 casdoor 的 oauth-provider 来提供迁移. 
调用流程: 新laf登录-〉统一casdoor-〉oauth by lafyun-〉callback to casdoor -〉callback to 新laf

> 4\. casdoor 的数据库选择，使用 sqlite 还是 postgresql 或 mysql（建议是 pg）

这块逻辑不应该让laf(或者启动laf的用户)关心与决策与维护
pg也挺重的,如果独立开发者只是想启动一个laf跑自己的代码,也可以支持sqlite?

### Prons
1. laf的代码可以更精简,剥离任何第三方,只提供oauth的OIDC登录支持
2. 方便对接其他公司内部的oauth或者LDAP模块,解耦合

### Cons
1. 如果不想使用sealos提供的统一登录casdoor,还是需要用户单独启动一套casdoor的镜像集群(或者任何oauth服务,在线的,免费的,都可以)
    可能的解决方案: 
    1. 提供sealos一件部署一个casdoor的集群镜像
    2. 提供单机可执行的dockerfile来启动一个独立的镜像
    3. 对于更轻量的开发者需求,提供一个默认的OIDC账户(不支持多账户登录)(yaf-cli)

**Comment by virgoone** [comment]
使用 https://logto.io/  这个基于 OIDC 的身份服务会不会更轻量一些，且技术栈基本是统一的，`logto` 是基于 node 开发的，不管是直接使用或者定制开发应该都是比较方便的

![image](https://user-images.githubusercontent.com/8540582/184098716-5f124ac5-a1b2-47d0-8b48-a6f444bd2593.png)

**Comment by cccy0** [comment]
> 使用 https://logto.io/ 这个基于 OIDC 的身份服务会不会更轻量一些，且技术栈基本是统一的，`logto` 是基于 node 开发的，不管是直接使用或者定制开发应该都是比较方便的，如果之后 laf 推出收费方案我理解应该基于一个比较方便定制的OIDC服务会更友好一些
> 
> ![image](https://user-images.githubusercontent.com/8540582/184098716-5f124ac5-a1b2-47d0-8b48-a6f444bd2593.png)

我觉得这个比起casdoor来说更精简实用, 对于数据部分与业务比较耦合的部分只保留了user这个表,  [这里](https://docs.logto.io/zh-cn/docs/recipes/manage-users/you-dont-need-a-user-table) 

对于云函数的开发者来讲, 他们可能只是仅仅需要 [连接器](https://docs.logto.io/zh-cn/docs/recipes/create-your-connector/) 这方面的功能 , 也就是casdoor中的provider

casdoor 与  logto大概功能对照

| 功能        | casdoor    |  logto |
| --------   | :-----:  | :----:  |
| 组织     | ✅ |   ❌     |
| 应用     | ✅ |   ✅     |
| 用户     | ✅ |   ✅     |
| 权限     | ✅ |   ❌     |
| 模型     | ✅ |   ❌     |
| 连接器/提供商     | ✅ |   ✅     |
| 资源     | ✅ |   ❌     |
| 令牌     | ✅ |   ❌     |
| webhook     | ✅ |   ❌     |
| 同步器     | ✅ |   ❌     |
| 证书     | ✅ |   ❌     |
| 商品     | ✅ |   ❌     |
| 付款     | ✅ |   ❌     |

**Comment by hsluoyz** [comment]
Hi all,

> 直接集成 casdoor，还是对 OIDC 做支持

建议直接集成casdoor，OIDC只是包了一层登录，提供的能力比较少，接入其他能力比如邮箱、手机还是要调用各种专属API，那还不如casdoor一套搞全啥都有。

> 是否保留 laf 内置的密码登陆方式，还是直接使用 casdoor 提供的全能力

随1一起解决了

> 怎样迁移旧有用户到 casdoor，尤其是没有明文密码的用户（以手机号为准、可使用验证码登陆或重置密码）

casdoor提供了syncer机制来实现与外部数据源的用户数据实时双向同步，可以自定义外部用户表结构，以映射到casdoor用户表结构。详见：https://casdoor.org/docs/syncer/overview

密码同步方面，casdoor通过采用与当前密码加密方式一样的加密算法，来实现casdoor密码校验行为的一致性。现在已经支持很多密码加密方式了：https://casdoor.org/docs/organization/overview 如果这边有需求增加新的加密方式，也可以提issue或PR来增加

> casdoor 的数据库选择，使用 sqlite 还是 postgresql 或 mysql（建议是 pg）

casdoor可以与laf共享一套数据库，只要是xorm支持的范围内

**Comment by fanux** [comment]
@maslow 赞成直接使用 casdoor, 有需求可以和 @hsluoyz 一起迭代，帮助两个社区共同成长，毕竟 sealos 已经完成了和 casdoor 对接了，到时所有的账户都可以统一。

**Comment by maslow** [comment]
> 使用 https://logto.io/ 这个基于 OIDC 的身份服务会不会更轻量一些，且技术栈基本是统一的，`logto` 是基于 node 开发的，不管是直接使用或者定制开发应该都是比较方便的
> 
> > laf的代码可以更精简,剥离任何第三方,只提供oauth的OIDC登录支持
> > 方便对接其他公司内部的oauth或者LDAP模块,解耦合

感谢推荐，我体验了一下 logto，确实很亮，小而美， 使用体验和文档都很友好～

**Comment by maslow** [comment]
感谢大佬参与指导 laf  @hsluoyz  

我们在 sealos 上已经在集成 casdoor 了， laf 与 sealos 同源同根， 应该也倾向于 casdoor， casdoor 的设计和功能更丰富一些，我们社区也有给 casdoor 提过 PR。 

> casdoor提供了syncer机制来实现与外部数据源的用户数据实时双向同步，可以自定义外部用户表结构，以映射到casdoor用户表结构。详见：https://casdoor.org/docs/syncer/overview

laf 是以 MongoDb 为主的， syncer 应该不支持这个。 

> casdoor可以与laf共享一套数据库，只要是xorm支持的范围内

相关文档看了，在 casdoor Q群我也咨询过，mongo 确实不在 xorm 支持范围内， 不过 外带一个 pg 也是能接受的。

另外，据我们同事反馈 casdoor 中有向 casbin.org 的外网请求， laf 和 sealos 都有离网环境的部署需求， 这块可能还要再研究一下。

**Comment by LeezQ** [comment]
1. 直接集成 casdoor，还是对 OIDC 做支持
>  建议直接集成，非 laf 的核心能力，能组合的尽量组合
2. 是否保留 laf 内置的密码登陆方式，还是直接使用 casdoor 提供的全能力
> 如果已经集成 casdoor ，且看到 casdoor 已经足够轻量的话，倾向于直接使用 casdoor 全能力吧。
3. casdoor vs logto
> 既然 sealos 已经使用 casdoor 了，我觉得 laf 也使用 casdoor 比较合理，后面的合作上也会更顺畅吧。

**Comment by maslow** [comment]
laf next 版已确定直接集成 casdoor，技术栈也与 sealos 高度一致。
