### ISSUE TITLE
laf-cli 在node.js 版本 < 16 时运行报错

### ISSUE THREAD

**Issue by djun** [labring/laf#254]
laf-cli 在node.js 版本 < 16 时运行报错，提示找不到模块等诸多错误；
已测试同一台机上升级node.js 到16，无此问题

**Comment by maslow** [comment]
@ dingzhenznen

**Comment by maslow** [comment]
laf next 版本大概率会使用 golang 重构 cli，现版本锁定，不再进行大升级，只做必要的 bug 修复。
