### ISSUE TITLE
定时触发器引导问题与定时触发器的拓展(cronjob)

### ISSUE THREAD

**Issue by moonrailgun** [labring/laf#258]
花了大约2个小时研究源码，发现触发器的机制存在以下问题: 

*以下内容特指定时触发器*

- 触发器的收集是在应用开始时进行初始化收集，意味着在启动后想要修改触发器只能通过重启应用才能实现触发器的更新

https://github.com/labring/laf/blob/11b5801dff2081015861926f305a966c59208225/packages/app-service/src/support/scheduler.ts#L30

- 触发的创建/更新/删除需要云函数发布。发布以后触发器配置才会被应用实例所使用(从应用数据库中的__published__functions获取)

这意味着用户不能先发布函数再创建触发器，而是得创建触发器后再发布函数，然后重启应用。

这个流程比较长，且缺失引导

> 另外初始化应用(000000)的发布函数似乎会写在`laf-sys`库中？

---------------

另外是一个需求，定时触发器应当支持cronjob，在定时任务场景来说cronjob应当是适应性更加好的解决方案(每小时0点，每天凌晨等等等等)

**Comment by maslow** [comment]
> 花了大约2个小时研究源码，发现触发器的机制存在以下问题:

👍

> * 触发器的收集是在应用开始时进行初始化收集，意味着在启动后想要修改触发器只能通过重启应用才能实现触发器的更新
> 
> https://github.com/labring/laf/blob/11b5801dff2081015861926f305a966c59208225/packages/app-service/src/support/scheduler.ts#L30
> 
> * 触发的创建/更新/删除需要云函数发布。发布以后触发器配置才会被应用实例所使用(从应用数据库中的__published__functions获取)
> 
> 这意味着用户不能先发布函数再创建触发器，而是得创建触发器后再发布函数，然后重启应用。
> 
> 这个流程比较长，且缺失引导

是的，我也觉得这块流程不好，用户创建好触发器 并不知道 要发布函数才能生效。 

> > 另外初始化应用(000000)的发布函数似乎会写在`laf-sys`库中？

SES(000000) 应用与普通应用的区别是没有分配独立的数据库，直接分配了 sys db，主要用于管理 laf sys 本身，在前期做 laf sys 扩展 & 运维工具使用。

> 另外是一个需求，定时触发器应当支持cronjob，在定时任务场景来说cronjob应当是适应性更加好的解决方案(每小时0点，每天凌晨等等等等)

cronjob 是有必要支持，我是打算将触发器从 app-service 中抽离出来，做一个统一的 trigger-service，重构这块。 让应用内的状态更少，还没有具体的想法呢

**Comment by moonrailgun** [comment]
> 是的，我也觉得这块流程不好，用户创建好触发器 并不知道 要发布函数才能生效。

最早我是发现得重启才能触发，因为更新除了会写入数据库以外并没有任何额外操作，而代码中很明显没有订阅mongodb变更的逻辑

后来发现还需要发布。即从平台db提交到应用db才能生效。

----------

本来是打算提交cronjob的feature的，因为我想尝试做一个定时机器人。但是看了代码以后我发现这块代码的设计不是很好，可能需要你来重新梳理/设计一下

**Comment by maslow** [comment]
这个帖子提的好，我打算在 v0.9 版本中将触发器重构，尽可能的去除 app-service 中的状态，为未来的绅缩扩展铺路。

**Comment by maslow** [comment]
定时触发器在 laf next 版本中， 将会使用 CronJob 实现（可能会直接使用 k8s CronJob）
