### ISSUE TITLE
【NoSuchKey】静态网站托管使用不了

### ISSUE THREAD

**Issue by yenche123** [labring/laf#268]
访问的时候，回报了以下的结果：
![image](https://user-images.githubusercontent.com/28533125/184504895-2491d97b-554b-444d-b90c-303b3df4f1bb.png)
<br>
我是在 console 一个个上传 dist 文件的，不知道哪一步出错了，访问不了
<br>
![image](https://user-images.githubusercontent.com/28533125/184504960-c05f6f21-21ea-4883-9c5e-9593f35007d5.png)
![image](https://user-images.githubusercontent.com/28533125/184504970-9a2dd15e-d9ba-42b2-8661-065115d2ceec.png)

**Comment by maslow** [comment]
got.

 lafyun.com 上的静态托管，为规避可能的法律风险，当前平台分配二级域名是不支持直接访问的， 使用自定义域名可以。

后面会逐步完善这块机制。

**Comment by yenche123** [comment]
@maslow 感谢！我已绑定自己的域名了，可以打开网站首页。
但我的网站是 spa，直接从浏览器地址栏访问网站的 `子路径` 时还是会显示【NoSuchKey】，请问要怎么配置呢？

**Comment by maslow** [comment]
spa 路由建议先使用 锚点链接，后面会支持 子路径重定向 的配置，现在还不支持
