### ISSUE TITLE
laf-cli 能下载到已被删除的云函数

### ISSUE THREAD

**Issue by yenche123** [labring/laf#269]
当前环境云函数只有如下 5 个：
![image](https://user-images.githubusercontent.com/28533125/184505418-179af524-20b1-41cc-959f-29da387e4438.png)
<br>
使用 `laf init -s APPID` 却能下载到那些已经被删除的云函数，如下所示：
![image](https://user-images.githubusercontent.com/28533125/184505449-1166cd0c-eda1-47f1-a220-b92cff325571.png)

**Comment by maslow** [comment]
是能下载到被删除的， 还是被禁用的， 被禁用的 也没会显示在 web ui 中

**Comment by yenche123** [comment]
> 是能下载到被删除的， 还是被禁用的， 被禁用的 也没会显示在 web ui 中

被删除的

**Comment by maslow** [comment]
ok 我来排查一下

**Comment by yenche123** [comment]
@maslow 
我复现了一下我的操作路径：
1. 我点击"垃圾桶"的图标来删除，提示我 `请先停用函数，再删除！`
2. 于是回到云函数列表上，点击函数名，把 `启用` 的 toggle 关闭，然后点击确认
3. 该云函数 item 直接从列表上消失
所以应该是 `停用`

所以这样操作下来，其实不算 bug，只是 console 后台无法操作删除
