### ISSUE TITLE
兼容 arm64 (实验机器为 树莓派4) 的一些要点记录

### ISSUE THREAD

**Issue by bytemo** [labring/laf#277]
首先是换掉 bitnami 系列镜像以及一些不支持arm的镜像，以下以 dev 模式下的 docker-compose.yaml 为例（修改后的文件随附如下，但此修改专为 树莓派 raspi 所定制，可能细节有所差异）：
[docker-compose.yaml.zip](https://github.com/labring/laf/files/9375555/docker-compose.yaml.zip)

## 首先是换掉所有 bitnami 系列镜像
![image](https://user-images.githubusercontent.com/31122096/185442957-4ab00399-a08b-4b56-a92f-3f2224bc3f10.png)

因为 bitnami 系列镜像做了很多的开箱即用的初始化工作，在换掉之后会在行为上有差异，需要自己去进行一些初始化操作，比如启动命令和参数的差异、需要手动生成 mongodb 的 key 文件等
对于 mongo ，MONGODB_USERNAME、MONGODB_PASSWORD、MONGODB_DATABASE 等在官方镜像中不支持，需要手动进入docker容器内部手动创建数据库和用户，此处可以考虑挂载一个初始化脚本来进行。

还有 openresty 镜像的替换
![image](https://user-images.githubusercontent.com/31122096/185444588-aed059d4-657a-4cbf-ab3e-3ad99eda74d9.png)

openresty 镜像替换之后需要更改 gateway 脚本的启动命令，并视情况可能需要 进入gateway 容器中配置 nginx。不过似乎在 0.8.6 中gateway 被替换了，此处或许存在不同
![image](https://user-images.githubusercontent.com/31122096/185444512-5112a5ae-cc20-4cdd-87a6-6fe60937e84b.png)

大概应该是这些，如果有遗漏发现跑不起来欢迎联系我补充。
在树莓派上跑了几周，没发现什么稳定性问题，资源占用在 1G 左右
![image](https://user-images.githubusercontent.com/31122096/185444307-33b6778e-54b3-4c99-95cb-466199cd8c76.png)

**Comment by maslow** [comment]
赞，这个指导很详细了

**Comment by maslow** [comment]
因近期要推出 laf next 版本， 架构调整较大， arm 的支持将会在 next 中处理， laf next 将天然支持 arm/amd 架构。
