### ISSUE TITLE
feat: mount volumes in app services when using k8s

### ISSUE THREAD

**Issue by zsnmwy** [labring/laf#283]
## Want

When storing large files or sharing some files with others, need to mount volumes in `app services` when using k8s.

Like:
- NFS
- StroageClass

## Now

`instance-kubernetes-driver` is not supporting mount volumes.

https://github.com/labring/laf/blob/f118412c422acc0a85fe4f07163a0422af38255a/packages/instance-controller/src/support/instance-kubernetes-driver.ts#L129-L204

**Comment by skyoct** [comment]
Why not consider using cloud storage?

**Comment by zsnmwy** [comment]
Cloud storage can not cover all sences.

---
Now I want to process 30GB+ videos and files in the functions.
Using the video stream process with minio is not enough to solve.
That means I need a large temporary file system.
If I store the file in the container, that means the node disk will be full when the services accept multiple requests.

---
Because of the business history, some files are stored on the NFS  server.
I can mount the NFS server in the code. But it's not a graceful solution.
I need to check the mount path in each function.

**Comment by maslow** [comment]
That would be a meaningful feature. 

In Kubernetes, OpenEBS + PVC can be used to automatically allocate temporary storage resources to applications. 

（You should still use cloud storage for persistent storage.
