### ISSUE TITLE
运行时上下文是否可以加入原生req?

### ISSUE THREAD

**Issue by moonrailgun** [labring/laf#290]
不清楚是否刻意没有加入?

![image](https://user-images.githubusercontent.com/6964737/186383546-0d64c19e-a981-4de0-8ab5-3610873fdac0.png)

**Comment by maslow** [comment]
其实是可以考虑直接使用原生 req，这块应该没什么问题。 
最初是想制定一个 统一的 入参，未来可以有更多扩展手段。

**Comment by maslow** [comment]
有道理， 能具体举例子吗，方便理解

**Comment by moonrailgun** [comment]
比方说我有一个koa应用。那我就可以直接使用 koa.callback()(req, res) 来直接把现成的应用集成到 laf 中

这是一个vercel的case
https://github.com/DIYgod/RSSHub/blob/master/api/vercel.js

**Comment by maslow** [comment]
这个需求很有价值，有几个疑问要请教：
1. 当前 app-service 是用 express 实现的， 如果暴露 req, res 当前也是 express 的，还是会出现不能直接用的情况
2. 是否有充分的理由切为 koa 实现
3. 无论暴露 express req / koa req，都与当前的 interface 不兼容，现有云函数的兼容有没有好的手段

最重要的是，使用 koa req interface，未来是否还会面临此 interface 的调整， 会再次面对 问题（3），存量生态产物的处理是关键问题。

**Comment by moonrailgun** [comment]
首先不是要切换koa。

建议使用node http 的 req对象。完整的名字我记得叫 incomingrequest(可能不对) 。因为所有的框架都需要兼容这个对象的数据（基于这个的原始数据来解析）

express的req对象是集成自nodejs的原生req对象的。这个没有问题。

建议是额外增加req的暴露(反正都暴露res了)，这个是增加更新，不会对现有的项目产生break change的吧

**Comment by maslow** [comment]
了解，认同 extra req 的方式，没有 break change。
另外，node native req （IncomingRequest) 等我再看一下其参数和结构， 应该没问题
