### ISSUE TITLE
Laf可以支持redis吗，每次请求都走数据库，数据库压力有点大

### ISSUE THREAD

**Issue by akiiity** [labring/laf#294]

**Comment by maslow** [comment]
说说你的具体场景，哪种场景下遇到了瓶颈，是否考虑使用 cloud shared 缓解？

**Comment by akiiity** [comment]
您好，我只擅长前端，然后想看看能否使用Laf作为后端，帮助我完成开发（我对您说的cloud shared不是很了解）。场景是开发一款电商选品工具，用户在日常使用过程中，会频繁的查询数据（核心功能）。根据我初步对Lafyun的体验发现Laf好像并没有什么缓存的策略，每次请求都会访问数据库，所以有这个需求。

**Comment by maslow** [comment]
redis 的支持是在计划之中的，只是还在调研当前的场景，是否刚需。 你的建议很重要，我会重新考虑这个需求的优先级
