### ISSUE TITLE
从哪里可以了解到该项目的架构较细的文档？

### ISSUE THREAD

**Issue by liujunzheng** [labring/laf#298]
例如：
1，目前只能通过源码去看每个模块的代表含义和功能大纲；
2，假设如果想对Web层这块修改或二次开发重构等，是否有一些文档可以参考呢，比如Web后端API的文档等？

**Comment by maslow** [comment]
现版确实没有这块材料，laf next 版本正在开发中， 最近几天将会编写新的架构文档发布

**Comment by haitaodesign** [comment]
> 现版确实没有这块材料，laf next 版本正在开发中， 最近几天将会编写新的架构文档发布

看laf next 引入了 golang，期待架构文档哈

**Comment by maslow** [comment]
- #353 
- #354 
- #352
