### ISSUE TITLE
希望云函数支持配置环境变量

### ISSUE THREAD

**Issue by yenche123** [labring/laf#304]
有些云函数的代码想直接开源，但涉及一些密钥（配置）就实现不了；如果多弄一套开源版的代码又很不方便维护。
我看了一下腾讯云那边，是支持这个功能的
![image](https://user-images.githubusercontent.com/28533125/187499601-8cc99ddb-8a8c-48c8-8cea-b856e5e7dbf2.png)

**Comment by maslow** [comment]
Forward to:
- laf roadmap: https://github.com/orgs/labring/projects/5/views/1
   - https://github.com/labring/laf-roadmap/issues/12

**Comment by yenche123** [comment]
👍
