### ISSUE TITLE
微信小程序原生开发，无法使用

### ISSUE THREAD

**Issue by extrastu** [labring/laf#312]
![image](https://user-images.githubusercontent.com/19451694/189062792-4d19f61e-27e5-430e-8a78-62324eeee864.png)

**Comment by maslow** [comment]
有没有快速复现的步骤能提供？

**Comment by youmengme** [comment]
试一下这样

```ts

const cloud = new Cloud({
  baseUrl: "https://{you appid}.lafyun.com",
  dbProxyUrl: "/proxy/app",
  getAccessToken: () => Taro.getStorageSync("access_token"),
  environment: EnvironmentType.H5, // 增加这个
});

```

**Comment by maslow** [comment]
@extrastu 不好意思这么迟才回复，这个问题我复现了一下，根据微信开发工具的文档， 微信小程序中需要单独「构建 npm 」，下面是官方文档地址：https://developers.weixin.qq.com/miniprogram/dev/devtools/npm.html

**Comment by maslow** [comment]
我没能复现你的问题， 我用你给的项目，构建后就没有那个错误了， 另外我也新建了 项目测试，也没有此问题， 还有更多信息？

**Comment by maslow** [comment]
不过，在成功构建 npm 后，原生小程序中还存在一个 "process not defined" 的报错， 这个错误已在 最新版的 sdk 中修复，升级 client sdk 后构建 npm:
```bash
npm i laf-client-sdk@0.8.12
```
