### ISSUE TITLE
云数据库是否可以提供RestAPI形式的调用

### ISSUE THREAD

**Issue by tomxin7** [labring/laf#315]
类似于Bmob云服务这样的
http://doc.bmobapp.com/data/restful/index.html#_3

**Comment by maslow** [comment]
暂时没有计划，能否提供更多想法、建议信息，以便做决策？比如：

- feature 的使用场景、能力及重要性说明
- 比现有方案带来更多特点/优势，如相比较于 client db sdk
- 认为比较好的实现思路或方案，如，这个能力是否可以通过复用云函数来实现 或是 内置到 laf app-service 中
- 等其它

**Comment by tomxin7** [comment]
因为经常会写HTML的单页应用，并不想创建一个vue项目，导致无法使用sdk，这种情况下，如果可以提供RestAPI的话，就可以很快的实现前端页面了，不过使用云函数自己封装一下也是可以的

**Comment by maslow** [comment]
明白，后续我再调研一下， 找到一个比较长期适合的方案。 

当前，可以通过直接引入 laf client bundle js 来解决你的场景， laf client sdk 可以像 jqeury 那样直接引入进 html 的， 只不过没有发布出来 对应的 bundle。 

我刚才编译了一份传上来，或者自己在 laf/packages/client-sdk 目录下运行 npm run build:bundle 自行构建也可：

https://oss.lafyun.com/tjwi8s-public/laf-client.bundle.js
