### ISSUE TITLE
微信支付v2版本回调无法正常解析

### ISSUE THREAD

**Issue by youmengme** [labring/laf#321]
因为微信支付V2版本的回调是XML格式的，laf没有正常解析

### 复现方式：
1. 新建test函数
2. 使用postman请求 body部分使用XML格式
<img width="720" alt="image" src="https://user-images.githubusercontent.com/27558572/190680695-4fa3c581-3ea5-4c3d-987a-9953fa6558fc.png">
结果如下：
<img width="933" alt="image" src="https://user-images.githubusercontent.com/27558572/190680826-14272e5d-24f7-493e-ad4e-95a9f399755f.png">

### 期望：
希望能将XML转化为JSON或者能让开发者获取到XML

**Comment by maslow** [comment]
https://github.com/labring/laf/commit/198027c5e95515b435fb72d12985a4c9b7e62a94

已支持 XML，请更新 app-service 镜像版本至： lafyun/app-service:0.8.11

**Comment by youmengme** [comment]
# 这样的开发团队 谁能不爱
# 这样的开发团队 谁能不爱
# 这样的开发团队 谁能不爱
# 这样的开发团队 谁能不爱

**Comment by youmengme** [comment]
# 这样的开发团队 谁能不爱
# 这样的开发团队 谁能不爱
# 这样的开发团队 谁能不爱
# 这样的开发团队 谁能不爱
# 这样的开发团队 谁能不爱
# 这样的开发团队 谁能不爱

> ps: 重启完服务之后如果云函数还是无法接收xml的body，请重启你的应用（我是这样才解决的）

**Comment by youmengme** [comment]
因laf解析出的xml非普通json对象（字段外多了层数组）所以补充一个工具函数，方便大家使用。

#### parse前
<img width="856" alt="image" src="https://user-images.githubusercontent.com/27558572/190843610-7edd0441-2cc5-44e6-9442-bf727c6fca12.png">

### parse后

<img width="742" alt="image" src="https://user-images.githubusercontent.com/27558572/190843648-c865d50b-e3b5-46a4-8d16-41d0d1361f63.png">

#### util

```ts
function parseLafyunXMLBody(body?: {
  xml: Record<string, Array<any> | any>
}) {
  const { xml } = body || {}
  if (!xml) {
    return {}
  }
  function parse(value) {
    if (!value) return value
    if (['string', 'number', 'boolean'].includes(typeof value)) {
      return value
    }
    if (Array.isArray(value)) {
      if (value?.length === 1) {
        return value[0]
      }
      return value.map(ele => parse(ele))
    }
    if (Object.prototype.toString.call(value) === '[object Object]') {
      return Object.keys(value).reduce((prev, curr) => {
        if (!prev[curr]) {
          prev[curr] = parse(xml[curr])
        }
        return prev
      }, {} as Record<string, any>)
    }
    return value
  }
  return parse(xml)
}
```
