### ISSUE TITLE
cloud.fetch timeout 问题

### ISSUE THREAD

**Issue by seewhy163** [labring/laf#325]
使用 cloud.fetch 请求stream数据， 在执行到十几秒的时候断开连接， 怀疑是超时时间问题。但是试了设置axios的timeout也没有生效。用同样的方法， 将cloud.fetch换成axios后，在本地node环境可以正常运行。
```
      const response = await cloud.fetch.post(DOMAIN, requestBody, {
            timeout: 240000,
            responseType: 'stream'
        });

        const stream = response.data;

        stream.on('data', data => {
            const frame = JSON.parse(new TextDecoder().decode(data));
            console.log('frame', frame);
       
        });

        stream.on('end', () => {
           
            console.log("stream done");
        });
```

**Comment by seewhy163** [comment]
找到原因了，是我代码问题，由于 TextDecoder 未定义。

另外在函数未执行完成之前，在管理后台中一直找不到日志信息和报错，最后是在 docker 日志中看到了这个错误。
请问是否能支持实时日志呢

**Comment by maslow** [comment]
实时日志会在下一个大版本中提供， 国庆前后。

**Comment by amzqing** [comment]
> 使用 cloud.fetch 请求stream数据， 在执行到十几秒的时候断开连接， 怀疑是超时时间问题。但是试了设置axios的timeout也没有生效。用同样的方法， 将cloud.fetch换成axios后，在本地node环境可以正常运行。
> 
> ```
>       const response = await cloud.fetch.post(DOMAIN, requestBody, {
>             timeout: 240000,
>             responseType: 'stream'
>         });
> 
>         const stream = response.data;
> 
>         stream.on('data', data => {
>             const frame = JSON.parse(new TextDecoder().decode(data));
>             console.log('frame', frame);
>        
>         });
> 
>         stream.on('end', () => {
>            
>             console.log("stream done");
>         });
> ```

您好，请问Laf如何返回stream请求？您尝试成功了吗？
