### ISSUE TITLE
[Bug] failed to create shim task

### ISSUE THREAD

**Issue by lwj1994** [labring/laf#358]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

Linux 5.1 (self-host)

### CPU Architecture

amd64

### laf version

1.0.x

### What happened

after docker-compose up 

```shell
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/Volumes/SA2000M8500G/libs/laf/deploy/docker-compose/gateway_dashboard_conf.yaml" to rootfs at "/usr/local/apisix-dashboard/conf/conf.yaml": mount /Volumes/SA2000M8500G/libs/laf/deploy/docker-compose/gateway_dashboard_conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```

### How to reproduce

docker-compose up 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
Based on the error information you provided, is there a permission problem in this directory? 
- You are advised to first check whether the file and directory exist. 
- Further check to see if its permissions are accessible? 
- Try it out with directory permissions open?

`/Volumes/SA2000M8500G/libs/laf/deploy/docker-compose/gateway_dashboard_conf.yaml`

**Comment by lwj1994** [comment]
[+] Running 8/0
 ⠿ Container docker-compose-etcd-1                    Running                          0.0s
 ⠿ Container docker-compose-app-console-1             Created                          0.0s
 ⠿ Container docker-compose-pull-app-service-image-1  Created                          0.0s
 ⠿ Container docker-compose-mongo-1                   Running                          0.0s
 ⠿ Container docker-compose-system-client-1           Created                          0.0s
 ⠿ Container docker-compose-oss-1                     Running                          0.0s
 ⠿ Container docker-compose-instance-controller-1     Running                          0.0s
 ⠿ Container docker-compose-system-server-1           Running                          0.0s
Attaching to docker-compose-apisix-dashboard-1, docker-compose-app-console-1, docker-compose-etcd-1, docker-compose-gateway-1, docker-compose-gateway-controller-1, docker-compose-instance-controller-1, docker-compose-mongo-1, docker-compose-oss-1, docker-compose-pull-app-service-image-1, docker-compose-system-client-1, docker-compose-system-server-1
docker-compose-mongo-1                   | mongodb 05:57:00.55
docker-compose-mongo-1                   | mongodb 05:57:00.55 Welcome to the Bitnami mongodb container
docker-compose-mongo-1                   | mongodb 05:57:00.55 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
docker-compose-mongo-1                   | mongodb 05:57:00.55 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
docker-compose-mongo-1                   | mongodb 05:57:00.55
docker-compose-mongo-1                   | mongodb 05:57:00.55 INFO  ==> ** Starting MongoDB setup **
docker-compose-mongo-1                   | mongodb 05:57:00.85 INFO  ==> Validating settings in MONGODB_* env vars...
docker-compose-instance-controller-1     | [2022-10-13T05:57:01.387] [INFO] server - server logging level is DEBUG
docker-compose-mongo-1                   | mongodb 05:57:12.31 INFO  ==> Initializing MongoDB...
docker-compose-system-server-1           | [2022-10-13T05:57:12.605] [INFO] server - server logging level is DEBUG
docker-compose-system-server-1           | [2022-10-13T05:57:12.848] [INFO] accessor:sys_db - accessor:sys_db logging level is DEBUG
docker-compose-system-server-1           | [2022-10-13T05:57:12.851] [INFO] accessor:sys_db - mongo accessor connecting...
docker-compose-mongo-1                   | mongodb 05:57:12.89 INFO  ==> Deploying MongoDB with persisted data...
docker-compose-mongo-1                   | mongodb 05:57:12.92 INFO  ==> Writing keyfile for replica set authentication...
docker-compose-oss-1 exited with code 137
docker-compose-mongo-1                   | mongodb 05:57:13.51 INFO  ==> ** MongoDB setup finished! **
docker-compose-mongo-1                   |
docker-compose-mongo-1                   | mongodb 05:57:13.72 INFO  ==> ** Starting MongoDB **
docker-compose-system-client-1           | openresty 05:57:14.03
docker-compose-system-client-1           | openresty 05:57:14.24 Welcome to the Bitnami openresty container
docker-compose-system-client-1           | openresty 05:57:14.29 Subscribe to project updates by watching https://github.com/bitnami/containers
docker-compose-pull-app-service-image-1  | pulled app-service image successful!
docker-compose-system-client-1           | openresty 05:57:14.29 Submit issues and feature requests at https://github.com/bitnami/containers/issues
docker-compose-system-client-1           | openresty 05:57:14.29
docker-compose-system-client-1           | openresty 05:57:14.29 INFO  ==> ** Starting OpenResty setup **
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/Volumes/SA2000M8500G/libs/laf/deploy/docker-compose/gateway_dashboard_conf.yaml" to rootfs at "/usr/local/apisix-dashboard/conf/conf.yaml": mount /Volumes/SA2000M8500G/libs/laf/deploy/docker-compose/gateway_dashboard_conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type



-rwxr-xr-x  1 lu  admin   928 Oct  2 11:24 gateway_conf.yaml
-rwxr-xr-x@ 1 lu  admin  3896 Oct  2 11:24 gateway_dashboard_conf.yaml

**Comment by maslow** [comment]
```
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/Volumes/SA2000M8500G/libs/laf/deploy/docker-compose/gateway_dashboard_conf.yaml" to rootfs at "/usr/local/apisix-dashboard/conf/conf.yaml": mount /Volumes/SA2000M8500G/libs/laf/deploy/docker-compose/gateway_dashboard_conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```

根据你的描述，这个问题可能不是 laf setup 的范畴，更像是 `docker & vbx` 某方面的问题，建议的排查方向是：
- 启动任意一个容器（非 laf ），挂载宿主机器目录，以测试在你的环境中，mount 是可正常工作或不可工作的
