### ISSUE TITLE
[Bug] 静态页面托管无法使用域名直接访问，The specified key does not exist.

### ISSUE THREAD

**Issue by Kenny-Ch** [labring/laf#359]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

Windows (self-host)

### CPU Architecture

amd64

### laf version

1.0.x

### What happened

直接访问静态网站托管的**访问域名**，会提示找不到`index.html`文件，但实际上文件存在存储桶中，使用`xx.oss.lafyun.com/index.html`可以访问
![微信图片_20221010202449](https://user-images.githubusercontent.com/54130213/194866780-2ea1e775-3289-4119-bf2a-2b449ba02d3f.png)

### How to reproduce

1. 将index.html文件放入存储桶中
2. 创建对应存储桶的网站托管
3. 访问网站托管的**访问域名**

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by skyoct** [comment]
@Kenny-Ch 我未复现该问题，请问你的代码是最近拉取部署的吗

**Comment by Kenny-Ch** [comment]
> @Kenny-Ch 我未复现该问题，请问你的代码是最近拉取部署的吗

@skyoct 我并没有部署代码，是使用https://console.lafyun.com/官网的测试服务，是因为官网不是最新的版本嘛？

**Comment by skyoct** [comment]
> @skyoct 我并没有部署代码，是使用https://console.lafyun.com/ 官网的测试服务，是因为官网不是最新的版本嘛？
@Kenny-Ch @maslow 在console.lafyun.com 复现了，可能console.lafyun.com和现在主分支代码不一致。

**Comment by maslow** [comment]
lafyun.com 当前确实有特殊的转发规则，在新版中会应用新的规则。
