### ISSUE TITLE
vm_root_exec command not found 

### ISSUE THREAD

**Issue by qingyggg** [labring/laf#381]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

Linux (self-host)

### CPU Architecture

amd64

### laf version

1.0.x

### What happened

when a souce scripts/start_vm.sh,the error occur,i see vm_root_exec command not found ,but the alias has been set.but when i set  shopt -s expand_aliases in start_vm.sh,the error disappeared.because i use bash in linux .

### How to reproduce

add 'shopt -s expand_aliases ' command in scripts/start_vm.sh before set alias

### Debug logs

...

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
The scripts only works well on MacOS by now.  May you provide the win/linux version with PR?

**Comment by qingyggg** [comment]
I try,but I need to test  it until it run correctly

**Comment by qingyggg** [comment]
https://github.com/qingyggg/laf-extra-start-shell-script.git

**Comment by qingyggg** [comment]
linux version has been finished,you can try
