### ISSUE TITLE
[Multilevel Routing] multilevel routing for cloud functions

### ISSUE THREAD

**Issue by Pidbid** [labring/laf#384]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

# Overview
1. Creating a function named Fun_1 and opening HTTP access.
2. We can use POST and GET methods to https://domain.com/fun_1, but we can not access https://domain.com/fun_1/a or https://domain.com/fun_1/b. The laf web server will return text response. It just like "Cannot GET fun_1/a".
3. So, We want to laf server can access multilevel routing for cloud functions.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
Thanks for ur suggestion. Sorry it took so long to reply. This capability was planned for v1.0 and is now on our roadmap.

**Comment by maslow** [comment]
Feature supported.
