### ISSUE TITLE
[Question] how to create triggers using cloud functions

### ISSUE THREAD

**Issue by youmengme** [labring/laf#389]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Question

I have a requirement to dynamically create timed tasks. I need to dynamically create timed (cron) triggers in laf cloud functions. Can I implement this requirement in v0.8.6? (I think other issues use english. so...)

**Comment by maslow** [comment]
This capability is not supported. Unless you call laf sys api to operate triggers by yourself
