### ISSUE TITLE
[Bug] Bug title 

### ISSUE THREAD

**Issue by qingyggg** [labring/laf#390]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

Linux (self-host)

### CPU Architecture

amd64

### Versions

OS: Ubuntu 22.04.1 LTS x86_64
laf:1.0

### What happened

I start start_vm.sh,the shell tool excute this shell script ,things are going well,but when excute `vm_root_exec sealos run docker.io/labring/user-controller:dev `,error occur

### How to reproduce

.

### Debug logs

2022-11-03T20:02:57 info start to install app in this cluster
Trying to pull docker.io/labring/user-controller:dev...
2022-11-03T20:03:01 error Applied to cluster error: initializing source docker://labring/user-controller:dev: reading manifest dev in docker.io/labring/user-controller: errors:
denied: requested access to the resource is denied
unauthorized: authentication required

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
Got.  This would be resolved soon.
