### ISSUE TITLE
[Bug] make run error

### ISSUE THREAD

**Issue by qingyggg** [labring/laf#396]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

Linux (self-host)

### CPU Architecture

amd64

### Versions

laf:1.0
linux:Ubuntu

### What happened

I set up sealos cluster that was initialed by start_vm.sh,I cd to the /controllers/database,and run the `make run `,then error appear

### How to reproduce

.

### Debug logs

alice@alice-B365-M-AORUS-ELITE:~/Desktop/demos/laf/controllers/database$ make run
/home/alice/Desktop/demos/laf/controllers/database/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/home/alice/Desktop/demos/laf/controllers/database/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
go fmt ./...
go vet ./...
go run ./main.go
1.6676308733679698e+09	ERROR	Failed to get API Group-Resources	{"error": "Get \"https://10.242.246.127:6443/api?timeout=32s\": context deadline exceeded - error from a previous attempt: EOF"}
sigs.k8s.io/controller-runtime/pkg/cluster.New
	/home/alice/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/cluster/cluster.go:160
sigs.k8s.io/controller-runtime/pkg/manager.New
	/home/alice/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/manager/manager.go:322
main.main
	/home/alice/Desktop/demos/laf/controllers/database/main.go:68
runtime.main
	/usr/local/go/src/runtime/proc.go:250
1.6676308733682706e+09	ERROR	setup	unable to start manager	{"error": "Get \"https://10.242.246.127:6443/api?timeout=32s\": context deadline exceeded - error from a previous attempt: EOF"}
main.main
	/home/alice/Desktop/demos/laf/controllers/database/main.go:88
runtime.main
	/usr/local/go/src/runtime/proc.go:250
exit status 1
make: *** [Makefile:73: run] Error 1

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
According to the log information you provided, it should be that your kubernetes api server is inaccessible? Please check whether the cluster is available:

> 1.6676308733679698e+09 ERROR Failed to get API Group-Resources {"error": "Get "[https://10.242.246.127:6443/api?timeout=32s\](https://10.242.246.127:6443/api?timeout=32s%5C)": context deadline exceeded - error from a previous attempt: EOF"}
