### ISSUE TITLE
如何只通过http请求来获取到云存储的数据

### ISSUE THREAD

**Issue by aiwalle** [labring/laf#398]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Question

大佬，请教一个问题
我看下来对于云存储的操作都需要通过miniIO
我是一个iOS的开发者，ios似乎没有miniIO相关的sdk
怎么能只通过普通的http请求来获取到云存储的对象呢
非常感谢您们团队提供这么好用的工具，感恩

**Comment by skyoct** [comment]
@aiwalle 如果只是获取云存储对象，直接通过http地址访问即可。如果需要上传文件等操作，可以尝试使用aws s3 ios sdk, 例如：https://github.com/calvinjia/cookbook/blob/master/docs/aws-sdk-for-iOS-with-minio.md

**Comment by aiwalle** [comment]
> @aiwalle 如果只是获取云存储对象，直接通过http地址访问即可。如果需要上传文件等操作，可以尝试使用aws s3 ios sdk, 例如：https://github.com/calvinjia/cookbook/blob/master/docs/aws-sdk-for-iOS-with-minio.md

谢谢您的解答，我研究看看

**Comment by maslow** [comment]
https://min.io/docs/minio/linux/developers/javascript/API.html#presignedUrl

- 针对私有访问的文件，可在云函数中生成对应文件的 签名 url 返回给 ios 端访问
- 针对 public read 的文件，可直接访问文件的 http url，无需签名和 sdk
- 如必需要在 ios 端通过 sdk 操作文件的话，https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-mobile-sdks.html
