### ISSUE TITLE
[Question] 请问有没有FlutterSDK

### ISSUE THREAD

**Issue by iletleon** [labring/laf#400]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Question

没找到所以来问下!

**Comment by maslow** [comment]
暂无 flutter sdk，推荐使用 http 直接调用云函数，在 flutter 环境中。

若有兴趣，希望由社区来贡献 flutter sdk，
这个仓库是过去实验性的 flutter sdk，已不在维护， 可能无法正常使用，可供参考。

https://github.com/lafjs/laf-client-dart

**Comment by iletleon** [comment]
> 

好的谢谢
