### ISSUE TITLE
Websocket 怎么获取唯一连接id

### ISSUE THREAD

**Issue by htfc786** [labring/laf#416]
### Search before asking

- [x] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Question

我想获取每个 WebSocket 连接唯一的id，文档里好像没有说如何获取，问一下如何获取连接的唯一id？感谢解答

**Comment by maslow** [comment]
laf 支持的是标准 websocket，不包括这块逻辑，这部分应该由 开发者 自行 维护。
我惯用的方式是 给 socket 对象增加一个 id 字段，可以是 uid 或 类 session id。 
```bash
conn['id'] = user.id
```
