### ISSUE TITLE
本机部署怎么能让局域网机器访问到

### ISSUE THREAD

**Issue by lxxself** [labring/laf#419]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Question

在局域网机器 docker 部署后，本机网络是可以访问http://dyzl6w.127-0-0-1.nip.io:8000/，那在局域网其他机器如何访问到呢？尝试过端口转发，不行。一定需要限定域名和绑定域名么？

**Comment by maslow** [comment]
是的，laf 应用的流量区分、分发 依赖域名。 如果需要局域网内其它机器能访问的话， 可以考虑用这样的域名：
192-168-M-N-nip.io
