### ISSUE TITLE
[Bug] Bug title ubuntu development environment set

### ISSUE THREAD

**Issue by qingyggg** [labring/laf#422]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

Linux (self-host)

### CPU Architecture

amd64

### Versions

laf:main

### What happened

1.set laf develop environment
2.permission denied

### How to reproduce

1.modify deploy/scripts/README.md
# setup k8s cluster
sudo sh install-k8s.sh

# setup laf core
sudo sh install-laf-core.sh

# apply laf cluster resources
sudo kubectl apply -f init-laf/

2. add sudo to per kubectl or helm command in install-laf-core.sh file 

### Debug logs

.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
Use sudo ?
