### ISSUE TITLE
[Bug] cant do crd test in linux

### ISSUE THREAD

**Issue by qingyggg** [labring/laf#428]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

Linux (self-host)

### CPU Architecture

amd64

### Versions

branch:main

### What happened

1.after I successfully install laf core and sealos cluster execute  properly
2.run make test command in (~/Desktop/workspace/labring/laf/core/controllers/database)
3.error occur

### How to reproduce

possible:
1.commonly,"/.kube/config" is in the home directory in linux ,such as /home/alice/.kube/config
2.but my k8s config file is in the /root/.kube directory!!!!
3.I guess the reason may be in sealos that the os enforce me add 'sudo' prefix when I am running sealos command ,other wise,the terminal will tell you "permission denied"
4.but I couldn't found which part of logic found kube config file when I test crd
5.thanks for solve this problem!!!

### Debug logs

make test
/home/alice/Desktop/workspace/labring/laf/core/controllers/database/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/home/alice/Desktop/workspace/labring/laf/core/controllers/database/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
go fmt ./...
go vet ./...
go test ./tests/e2e -v
=== RUN   TestDbCreate
=== RUN   TestDbCreate/create_db_should_be_ok
--- FAIL: TestDbCreate (0.00s)
    --- FAIL: TestDbCreate/create_db_should_be_ok (0.00s)
panic: stat /home/alice/.kube/config: no such file or directory [recovered]
        panic: stat /home/alice/.kube/config: no such file or directory

goroutine 8 [running]:
testing.tRunner.func1.2({0x1436be0, 0xc00045be50})
        /opt/go/src/testing/testing.go:1396 +0x24e
testing.tRunner.func1()
        /opt/go/src/testing/testing.go:1399 +0x39f
panic({0x1436be0, 0xc00045be50})
        /opt/go/src/runtime/panic.go:884 +0x212
github.com/labring/laf/core/tests/api.GetDefaultKubernetesClient()
        /home/alice/Desktop/workspace/labring/laf/core/tests/api/kubernetes.go:37 +0x7b
github.com/labring/laf/core/tests/api.EnsureNamespace({0x1658cc7, 0x13})
        /home/alice/Desktop/workspace/labring/laf/core/tests/api/cluster.go:27 +0x27
github.com/labring/laf/core/controllers/database/tests/e2e.TestDbCreate.func1(0xc000782d00)
        /home/alice/Desktop/workspace/labring/laf/core/controllers/database/tests/e2e/db_create_test.go:18 +0x3f
testing.tRunner(0xc000782d00, 0x1720c10)
        /opt/go/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
        /opt/go/src/testing/testing.go:1493 +0x35f
FAIL    github.com/labring/laf/core/controllers/database/tests/e2e      0.015s
FAIL
make: *** [Makefile:61: test] Error 1

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
If you are sure that the .kube/config file exists locally, maybe make test does not have permission to access it?

**Comment by qingyggg** [comment]
This problem has been solved

**Comment by qingyggg** [comment]
I have type 'sudo -i -u root' and execute it,the crd test pass correctly
