### ISSUE TITLE
如何获取访问者ip

### ISSUE THREAD

**Issue by htfc786** [labring/laf#434]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Question

我想获取访问者ip和websocket连接者IP，文档里好像没有说，如何获取？

**Comment by maslow** [comment]
```console.log(ctx.headers) ```

**Comment by maslow** [comment]
https://github.com/labring/laf/discussions/285

**Comment by htfc786** [comment]
感谢大佬回复，但是为什么我用 WebSocket 这里显示 undefined 
![image](https://user-images.githubusercontent.com/85735251/204181449-39a09b03-c7b5-42a3-82c6-2b15d64e32fa.png)
![image](https://user-images.githubusercontent.com/85735251/204183288-c38edfe2-cf76-4edc-bdf0-d1c437940f7a.png)
