### ISSUE TITLE
[Question] Is there a deployment document for integrating into existing k8s?

### ISSUE THREAD

**Issue by aliuq** [labring/laf#437]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Question

I have an exist kubernetes, How to deploy laf by hlem or klubectl instead of sealos

**Comment by maslow** [comment]
The current version of laf (v0.8) does not have a kubernetes deployment version, and you can use the docker deployment for v0.8. 

> The new version (v1.0) will support k8s deployment, but there is no release yet, and it is not available. When the new version is released, helm deployment will be provided, which can be used in any k8s environment.
