### ISSUE TITLE
LaF获取访问者ip显示undefined 

### ISSUE THREAD

**Issue by htfc786** [labring/laf#438]
感谢大佬回复，但是为什么我用 WebSocket 这里显示 undefined 
![image](https://user-images.githubusercontent.com/85735251/204181449-39a09b03-c7b5-42a3-82c6-2b15d64e32fa.png)
![image](https://user-images.githubusercontent.com/85735251/204183288-c38edfe2-cf76-4edc-bdf0-d1c437940f7a.png)

_Originally posted by @htfc786 in https://github.com/labring/laf/issues/434#issuecomment-1328475453_

**Comment by maslow** [comment]
连接成功后，应该是不能通过 ctx.headler 获取到 ip 了， 因为已经没有 http 请求了，更没有 header。

laf 云函数中提供的是标准的 web socket 对象，你可查询一下资料，看看 标准的 web socket 是怎样获取客户端 ip 的。

**Comment by htfc786** [comment]
我连接的时候获取的道吗？

**Comment by maslow** [comment]
我一时不太确定，可以在 connection 这个事件时 打印 ctx.headers 测试一下，若不行的话，我们一起再排查一下？

**Comment by htfc786** [comment]
感谢解答，如果不行我在开issues

**Comment by maslow** [comment]
> 感谢解答，如果不行我在开issues

也可不用，就在一个 issue 下讨论吧， 这样上下文 连续。

**Comment by htfc786** [comment]
感谢解答，可以获取，应该是 x-real-ip 吧
![image](https://user-images.githubusercontent.com/85735251/204255834-f023cb67-e93e-4881-9584-8ec8999706ec.png)

**Comment by maslow** [comment]
是的
