### ISSUE TITLE
[Bug] prisma push error

### ISSUE THREAD

**Issue by qingyggg** [labring/laf#461]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

Linux (self-host)

### CPU Architecture

amd64

### Versions

.

### What happened

1.install sealos and setup cluster
2.install crd
3.install node packages
4.npx prisma db push 
5.error occur

### How to reproduce

.

### Debug logs

npx prisma db push 
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db"
Error: MongoDB error
Server selection timeout: No available servers. Topology: { Type: ReplicaSetNoPrimary, Servers: [ { Address: mongo.laf.svc.cluster.local:27017, Type: Unknown, Error: failed to lookup address information: Name or service not known }, ] }
   0: migration_core::state::SchemaPush
             at migration-engine/core/src/state.rs:381

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
add local dns for `mongo.laf.svc.cluster.local` to 127.0.0.1

**Comment by qingyggg** [comment]
after modified /etc/hosts,and reset the dns cache,this is the new error log
------>
▶npx prisma db push
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db"
Error: MongoDB error
Server selection timeout: No available servers. Topology: { Type: ReplicaSetNoPrimary, Servers: [ { Address: mongo.laf.svc.cluster.local:27017, Type: Unknown, Error: Connection refused (os error 111) }, ] }
   0: migration_core::state::SchemaPush
             at migration-engine/core/src/state.rs:381
