### ISSUE TITLE
[Feature] Logs deletion

### ISSUE THREAD

**Issue by juukee** [labring/laf#468]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

When there are more and more cloud function logs, you need to delete some old logs to reduce data memory！

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by juukee** [comment]
Add log export function

**Comment by maslow** [comment]
Sorry it took so long to reply. This is an important suggestion. I will include this suggestion in our roadmap. 

Thanks for the feedback.

**Comment by nightwhite** [comment]
see this 
https://forum.laf.run/d/73
