### ISSUE TITLE
[Question] 数据库无法批量删除和添加

### ISSUE THREAD

**Issue by nightwhite** [labring/laf#470]
### Search before asking

- [x] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Question

文档写可以批量删除，但是实际不可以批量删除

另外没有批量添加数据库的功能

另外也没有删除集合的功能

**Comment by maslow** [comment]
具体是指哪块呢？ 批量删除和添加， 客户端还是云函数？

**Comment by LeezQ** [comment]
由于 LaF 还没提供良好的数据库备份、恢复能力，所以像「批量删除」以及删除「集合」这种高危操作 0.8 版本在界面上暂时没有提供，但是你可以通过写一个云函数来进行批量操作。
在 1.0 版本中会加上删除功能，但是会加强高危操作的二次确认，以防用户操作失误导致数据丢失。
另外后续也会设计数据库相关的备份方案。
