### ISSUE TITLE
[Feature] IDE context menu displays Chinese

### ISSUE THREAD

**Issue by juukee** [labring/laf#475]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

IDE context menu displays Chinese, Only English can be displayed now

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
Thanks for your suggestion, the current development manpower may not be able to quickly respond to this need, if you are interested, please help us to improve this problem.
