### ISSUE TITLE
[Feature] Add Redis

### ISSUE THREAD

**Issue by juukee** [labring/laf#476]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

Redis is widely used in the system. I hope it can be supported.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
I agree and have collected into the roadmap.

**Comment by fanux** [comment]
It seems more suitable to use sealos to provide redis or other databases and back-end capabilities

**Comment by zsnmwy** [comment]
I hope Laf can support Redis.
A single instance of Redis is used in a multi-tenant environment, which means multiple and different applications using the same Redis instance.
Using the prefix key to isolate the application should be fine.

Sealos can power the Redis cluster.

**Comment by maslow** [comment]
Sealos already support redis.

**Comment by solirpa** [comment]
@maslow laf 如何连接到 sealos 的 redis，貌似找不到有文档说明？

**Comment by solirpa** [comment]
@maslow laf 如何访问 sealos 部署的数据库？貌似没找到有任何文档说明？
