### ISSUE TITLE
[Feature] System exception notification

### ISSUE THREAD

**Issue by juukee** [labring/laf#477]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

If there are system exception notifications such as system exceptions, insufficient resources, or insufficient memory, you can notify through webhook。

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
Not yet. Can you describe the requirements in detail.

**Comment by juukee** [comment]
Like memory overflow, service interruption or stop, the application cannot run

**Comment by maslow** [comment]
We will support resource monitor in next release.   (in next week)
