### ISSUE TITLE
[Question] laf running on port 18000, did the nginx mapping, application service address but still have the old port number, lead to can't normal debugging

### ISSUE THREAD

**Issue by JZLeung** [labring/laf#484]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Question

控制台地址：`http://console.lafyun.127-0-0-1.nio/app-console/#/app/hmnmmx/dashboard/index`

服务地址：`http://hmnmmx.lafyun.127-0-0-1.nio:18000`

导致调试时会报跨域，无法正常调试。

>Access to XMLHttpRequest at 'http://hmnmmx.lafyun.127-0-0-1.nio:18000/debug/test' from origin 'http://hmnmmx.lafyun.127-0-0-1.nio' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

不带端口号访问云函数是正常的。

请问怎么修改？

附上配置文件：

```
# exposed port of laf services
PUBLISH_PORT=18000
PUBLISH_HTTPS_PORT=19443
```

**Comment by maslow** [comment]
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/7122237/216077536-03a94f85-92df-4705-8c5c-6c2e01808206.png">

补充说明， 这个情况是前端加了 反向代理， 所以要将 上图中 publish port 参数改为 实际 反代对外的端口（80），重启服务使其生效即可。
