### ISSUE TITLE
[Feature] Script for external data migration to laf

### ISSUE THREAD

**Issue by juukee** [labring/laf#485]
### Search before asking

- [X] #486

### Feature Request

External data migration needs to be increased, such as Alibaba Cloud, Tencent Cloud and Uniapp

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by skyoct** [comment]
@juukee Does external data specifically refer to mongodb data and object storage data？

**Comment by juukee** [comment]
> @juukee Does external data specifically refer to mongodb data and object storage data？

such as MySQL

**Comment by maslow** [comment]
Thanks for the suggestion. I have included this issue in our roadmap.

**Comment by juukee** [comment]
We need to import and export the database.

**Comment by maslow** [comment]
https://forum.laf.run/d/909

This may help.
