### ISSUE TITLE
How to customize path access?

### ISSUE THREAD

**Issue by htfc786** [labring/laf#487]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Question

如何自定义路径访问？
![image](https://user-images.githubusercontent.com/85735251/205897181-658e10ee-208f-4e62-aab4-b327709df48f.png)
如果自定义路径访问已经开发出来了并已经上线，当我什么也没说，请告诉我使用方法，谢谢。
我搜了一下，好像有人问了类似的问题，不过请继续往下看，
（源码从gitee上下载，GitHub太慢了！）
我根据报错的位置，知道函数是在（1）的位置被调用的，（2）的位置是根据名字去数据库里查询云函数数据，
![image](https://user-images.githubusercontent.com/85735251/205898593-0df6476e-87ac-4e67-9178-8953e4e212e2.png)
然后里面好像就是调用了一下数据库查了一下表
![image](https://user-images.githubusercontent.com/85735251/205899260-da1d3fd5-b376-4d0b-917f-eb916d28eed9.png)
有没有一种可能，就是在数据库表里面增加一列（可有可无的那种），存储自定义路径信息，然后每次先根据路径查询，如果没有在根据名称查询，在没有返回404，这样就可以自定义路径了！
本来是想自己写一个提一个pr，但是我环境都不会搭，我也没有用过mongodb数据库，看哐哐报错的样子，还是算了，但是还是把思路分享一下把，本人未成年人，就是随便看看，可能说的不好，见谅。

另外希望支持一下另一种url写法
比如：/albumapi/album/{albumid}/make/photo/{photoid}/del
希望可以把{albumid}和{photoid}里的数据一起传到云函数里面去，这好像是一种api写法，
感谢看到这里！

**Comment by htfc786** [comment]
额。。。我只是提供一个修改的建议，希望官方可以优化一下

**Comment by maslow** [comment]
感谢建议，而且这个实现思路也挺好的，我将在 1.0 的 beta 版中具体设计实现这个功能。
