### ISSUE TITLE
[Feature] Automatic update of cloud function dependency

### ISSUE THREAD

**Issue by juukee** [labring/laf#490]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

cloud function depend cant auto update by reboot, hopes more support can be provided and add the option switch of whether to update automatically

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
Can be more specific about it, I don't know what this mean.

**Comment by maslow** [comment]
> 

Got.

**Comment by maslow** [comment]
Fixed in v1.x.
