### ISSUE TITLE
[Feature] Data chart displayed on the application homepage

### ISSUE THREAD

**Issue by juukee** [labring/laf#491]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

Data chart displayed on the application homepage,Let users know the resource usage.
such as below:
![捕获](https://user-images.githubusercontent.com/28680837/205936190-f2aaa26f-2e91-4af5-9139-d1555277d555.PNG)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
Thank you for your suggestion, this function will be provided in future versions, temporarily haven't started to specific design.

@LeezQ

**Comment by LeezQ** [comment]
this feature is about `Dashboard` & `Data` product design, I think we need to finish this feature when we publish 1.0 official release. I'll mark it and close this issue.
