### ISSUE TITLE
[Feature] Cloud database record sorting

### ISSUE THREAD

**Issue by juukee** [labring/laf#492]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

The cloud database records need to be sorted according to the latest time. The latest records are at the top, and you want to increase the time of data records

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
This depends on the custom time field in the collection. 
May not be suitable for general-purpose use.
