### ISSUE TITLE
云函数如何调用云存储？

### ISSUE THREAD

**Issue by htfc786** [labring/laf#521]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Question

我想使用云存储功能，我去看了调用文档，真的没看懂。。。
如何调用增删改查功能啊？
顺便问一下，有没有什么高级功能，比如图片旋转、压缩什么的？
感谢解答

**Comment by maslow** [comment]
云存储是标准 s3接口，了解s3 API即可，同时 阿里云 腾讯云等的对象存储 都是 s3 api 兼容的，资料比较多，可以查一下，后面会增加更多使用实例

**Comment by htfc786** [comment]
大佬好，使用s3接口调用，我搜了一下，没搜到如何增删改查的方法，好像在 AssumeRoleCommand 传入对象，就可以运行，大佬您能告诉我，增删改查传入的对象分别是什么吗？感谢大佬
