### ISSUE TITLE
上传文件到bucket后，无法显示文件，也不能管理，网站托管也没有用

### ISSUE THREAD

**Issue by jikefan** [labring/laf#524]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Question

上传文件到bucket后，无法显示文件，也不能管理，网站托管也没有用

**Comment by maslow** [comment]
能提供更多信息吗？

**Comment by jikefan** [comment]
<img width="1363" alt="image" src="https://user-images.githubusercontent.com/50569006/207066657-d83e1a4e-7afb-49e3-93b3-7379584baff3.png">

我已经上传文件上去了，但是不显示文件。
我之前用的官方的试用就不行，所以在本地docker部署再次尝试，但是依然这个样子

**Comment by maslow** [comment]
需要提供更多信息，日志 or 其它， 因为没法复现 你的情况， 我本地部署和 lafyun 线上的都没有复现这个问题

**Comment by maslow** [comment]
<img width="1467" alt="image" src="https://user-images.githubusercontent.com/7122237/207068141-8f0a337f-205e-41b8-8ba6-1e73cd3dbd08.png">
刚试过在 lafyun 上新建了 bucket 和文件

**Comment by jikefan** [comment]
> 

<img width="768" alt="image" src="https://user-images.githubusercontent.com/50569006/207067969-6baa134b-b3ce-4299-8e3f-fe9e9bbed275.png">

- 那个展现bucket中文件夹的页面出现如此错误

**Comment by maslow** [comment]
👌 看一下文件请求的接口返回的是什么，报的什么错

**Comment by jikefan** [comment]
> 

我使用Chrome浏览器就没有错误了

**Comment by maslow** [comment]
OK 报错的浏览器是？

**Comment by jikefan** [comment]
> 👌 看一下文件请求的接口返回的是什么，报的什么错

<img width="782" alt="image" src="https://user-images.githubusercontent.com/50569006/207069834-e0cceb0a-48b3-4299-b6a3-82263e2608a0.png">

接口拿数据都是正常的，就是渲染到Safari浏览器出现bug

**Comment by maslow** [comment]
好的，我回头排查一下 safari 下的这个错误

**Comment by jikefan** [comment]
> 好的，我回头排查一下 safari 下的这个错误

谢谢你，加油大佬！
