### ISSUE TITLE
希望访问网站托管域名的时候，能够直接映射到index.html这样的文件

### ISSUE THREAD

**Issue by jikefan** [labring/laf#526]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

<img width="806" alt="image" src="https://user-images.githubusercontent.com/50569006/207072613-b9ab56f2-3710-41b1-9908-04201dd12d4e.png">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
私有部署的，开启 website 静态托管 后 有这个映射的，但 lafyun.com 上暂未开放。
