### ISSUE TITLE
如何使用s3接口调用云函数增删改查？

### ISSUE THREAD

**Issue by htfc786** [labring/laf#532]
大佬好，使用s3接口调用，我搜了一下，没搜到如何增删改查的方法，好像在 AssumeRoleCommand 传入对象，就可以运行，大佬您能告诉我，增删改查传入的对象分别是什么吗？感谢大佬
_Originally posted by @htfc786 in https://github.com/labring/laf/issues/521#issuecomment-1347784150_

**Comment by maslow** [comment]
s3 api 就是对文件进行操作的呀（增删查改）， AssumeRoleCommand 又是什么？

https://www.lafyun.com/guide/oss/
https://min.io/docs/minio/linux/developers/javascript/minio-javascript.html

**Comment by maslow** [comment]
这是使用 `@aws-sdk/client-s3` 操作文件的文档。 
https://www.npmjs.com/package/@aws-sdk/client-s3
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/index.html

**Comment by htfc786** [comment]
感谢大佬解答，但是，我是真的看不懂这个英文文档。。。
就是，您能不能告诉我增删改查的api啊，感谢大佬支持

**Comment by maslow** [comment]
可以在群里问一下，我手边也没有现成的例子，等我忙完最近发版的事，来着手补充这方面案例

**Comment by maslow** [comment]
https://github.com/labring/laf/blob/v0.8/packages/app-console/src/views/storage/files.vue

我帮你找到， laf 控制台中 文件增删查改的代码位置， 供你参考。

**Comment by htfc786** [comment]
感谢大佬，加油！
