### ISSUE TITLE
[Feature] Cloud function fixed IP

### ISSUE THREAD

**Issue by juukee** [labring/laf#544]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

Serverless does not have a fixed server IP by default, but some third-party systems require a fixed IP white list。like this:
'''
https://uniapp.dcloud.net.cn/uniCloud/cf-functions.html#eip
'''

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by juukee** [comment]
@maslow can lafyun provide ip list for us？

**Comment by maslow** [comment]
> 

- 39.101.194.103
- 39.99.239.142

**Comment by juukee** [comment]
tks
