### ISSUE TITLE
doc error:  type error in database ql field() method

### ISSUE THREAD

**Issue by htfc786** [labring/laf#585]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Question

数据库db field代码提示报错，
程序是可以跑通的啊
![image](https://user-images.githubusercontent.com/85735251/209508080-23110c75-e76a-4039-824f-7a61e6cabdaf.png)
![image](https://user-images.githubusercontent.com/85735251/209513256-6b25dab4-f873-4605-a745-5a0657dd5bf1.png)
![image](https://user-images.githubusercontent.com/85735251/209508083-6ff47174-9bd6-42ce-8b86-97d46b34444b.png)

**Comment by jveay** [comment]
应该是文档那边有错误。用 field({ "age": 1 })

**Comment by maslow** [comment]
文档错误，应该修改文档。
