### ISSUE TITLE
[Feature] 1.0 Automatically refresh data

### ISSUE THREAD

**Issue by juukee** [labring/laf#721]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

When you use cloud function debugging, if you change the data, the database will not automatically refresh the data.
My suggestion is to add a refresh button on the function。

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
Thanks for your suggestion, this feature has been fixed in # 748 and will be released in the next release.
