### ISSUE TITLE
[Feature] Unable to change cloud function name after created

### ISSUE THREAD

**Issue by sulnong** [labring/laf#722]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

After create cloud function, can not change its name, name input frame is disabled
this is an very essential feature for developing cloud functions

<img width="1272" alt="image" src="https://user-images.githubusercontent.com/37979965/216643174-3e76cfcd-428f-4d0a-8efa-452f05551023.png">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
The current cloud function does not support name modification.
