### ISSUE TITLE
[Bug] debugging problem

### ISSUE THREAD

**Issue by juukee** [labring/laf#723]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

When two windows are in cloud development, click Debug to debug two cloud functions at the same time. The operation is normally performed on one page

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
Thanks for your feedback. I don't quite understand the problem you described. Could you tell us the simple steps to reproduce it?

**Comment by juukee** [comment]
1.Open two cloud function development interfaces
2.Click Debug on a page
3.You can see in the log that two cloud functions will be requested for debugging at the same time

**Comment by maslow** [comment]
@LeezQ @kongwy229  Any updates about this?
