### ISSUE TITLE
[Feature] Open cloud function template market

### ISSUE THREAD

**Issue by juukee** [labring/laf#725]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

We urgently need to open the cloud function template market to facilitate communication and learning and reduce duplicate code

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
Thanks for the suggestion, we have scheduled this feature.

**Comment by maslow** [comment]
https://github.com/orgs/labring/projects/5/views/17?pane=issue&itemId=12373754

**Comment by maslow** [comment]
Feature done.
