### ISSUE TITLE
[Feature]  The application domain name is inconsistent with the OSS domain name

### ISSUE THREAD

**Issue by juukee** [labring/laf#726]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

Some applications need to set the callback url, but need to verify the ownership of the domain name, but the application domain name is inconsistent with the OSS domain name

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
Each bucket has its own separate domain name. Does your scenario support verifying multiple domains? 
Also add verification of OSS domain, if possible.

**Comment by juukee** [comment]
WeChat development does not support multiple domain name verification. So how to solve this problem?
