### ISSUE TITLE
[Feature] Browser compatibility issues

### ISSUE THREAD

**Issue by juukee** [labring/laf#727]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

Version 0.8 can be developed in Sogou browser, but version 1.0 cannot. Other browsers have not been tested yet

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
Sorry about that.  At this stage, we will give priority to supporting and testing Chrome. We recommend using Chrome, no other browser is guaranteed now.

Or are you interested in helping US support multiple browsers?
