### ISSUE TITLE
[Bug] Can run laf app while installing package "sharp"

### ISSUE THREAD

**Issue by nightwhite** [labring/laf#731]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

lafyun.com

### CPU Architecture

amd64

### Versions

laf 1.0

### What happened

![image](https://user-images.githubusercontent.com/22722256/216839696-9a746efc-9661-4852-afd8-232adcda8738.png)
一直start中,启动不了

### How to reproduce

NPM依赖中添加名为 sharp的npm,后一直是starting

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by nightwhite** [comment]
![image](https://user-images.githubusercontent.com/22722256/216839929-79861c55-48bb-4acb-a97f-2b1d8cebd09e.png)
![image](https://user-images.githubusercontent.com/22722256/216839950-6c4a0627-6400-4cbf-ae00-e5f46dbb6d96.png)
laf 0.8版本即便依赖已经安装了sharp,也找不到该依赖

**Comment by nightwhite** [comment]
经过反复测试,laf 1.0安装sharp后 starting会很久,大概5分钟后才启动成功

**Comment by nightwhite** [comment]
经过反复测试,laf 0.8重启服务大概5分钟之后才能正常找到该依赖

**Comment by nightwhite** [comment]
貌似需要配置网络或者官方提供的安装方法

https://sharp.pixelplumbing.com/install#chinese-mirror

**Comment by maslow** [comment]
Got.
