### ISSUE TITLE
[Bug] Install the npm package  @tensorflow/tfjs-node, failed

### ISSUE THREAD

**Issue by nightwhite** [labring/laf#732]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

lafyun.com

### CPU Architecture

amd64

### Versions

Time: 2023-02-06 04:29:58
Request ID: 18f32623-a400-43eb-a727-8dbc17a6f82f
Function: checkImage
Content:
'Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /app/node_modules/@tensorflow/tfjs-node/lib/napi-v8/../../deps/lib/libtensorflow.so.2)' 'node:internal/modules/cjs/loader:1302\n' +
  '  return process.dlopen(module, path.toNamespacedPath(filename));\n' +
  '                 ^\n' +
  '\n' +
  'Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /app/node_modules/@tensorflow/tfjs-node/lib/napi-v8/../../deps/lib/libtensorflow.so.2)\n' +
  '    at Module._extensions..node (node:internal/modules/cjs/loader:1302:18)\n' +
  '    at Module.load (node:internal/modules/cjs/loader:1081:32)\n' +
  '    at Module._load (node:internal/modules/cjs/loader:922:12)\n' +
  '    at Module.require (node:internal/modules/cjs/loader:1105:19)\n' +
  '    at require (node:internal/modules/cjs/helpers:103:18)\n' +
  '    at Object.<anonymous> (/app/node_modules/@tensorflow/tfjs-node/dist/index.js:72:16)\n' +
  '    at Module._compile (node:internal/modules/cjs/loader:1218:14)\n' +
  '    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)\n' +
  '    at Module.load (node:internal/modules/cjs/loader:1081:32)\n' +
  '    at Module._load (node:internal/modules/cjs/loader:922:12)'
![image](https://user-images.githubusercontent.com/22722256/216843226-410cf197-f8d0-4d33-8b13-a8c3b625005d.png)

### What happened

The code is as follows:
![image](https://user-images.githubusercontent.com/22722256/216843278-b3973b4e-2be2-43ba-8b01-ee5bcfa5c666.png)

### How to reproduce

New NPM dependencies: @tensorflow/tfjs-node
The require run in the cloud function then reports an error

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by nightwhite** [comment]
laf 1.0 无法删除该依赖 @tensorflow/tfjs-node
![image](https://user-images.githubusercontent.com/22722256/216846351-9e8a83c7-7236-4d59-bf74-bfe68111e8e3.png)

**Comment by maslow** [comment]
Got.
