### ISSUE TITLE
[Feature] Cloud function timing trigger is not on time

### ISSUE THREAD

**Issue by juukee** [labring/laf#737]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

Cloud function timing trigger is not on time
![微信图片_20230206153150](https://user-images.githubusercontent.com/28680837/216911647-726ccdec-9caf-4c9f-91fd-fa3ec30aef2b.png)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
Would be fixed in next release (v1)
