### ISSUE TITLE
[Feature] 新版数据库页面没有刷新功能

### ISSUE THREAD

**Issue by AeCode-call** [labring/laf#745]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

![image](https://user-images.githubusercontent.com/69137571/217142722-60af8018-1e42-4f30-9698-b67d6878ac69.png) 

新版数据库页面没有刷新功能，当我通过函数向数据库添加数据时数据库页面展示的数据没有刷新，且切换云函数页面再回到数据库页面时也不刷新，只能通过点击浏览器的刷新按钮或切换数据集合才能刷新数据。 

能不能添加一个刷新按钮，或者直接数据库刷新数据时刷新页面，或者定时拉去一下数据库信息

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
Fixed.
