### ISSUE TITLE
[Bug] The change you are trying to make would violate the required relation 'ApplicationToStorageUser' between the `Application` and `StorageUser` models

### ISSUE THREAD

**Issue by xianhaosui** [labring/laf#746]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

Linux (self-host)

### CPU Architecture

amd64

### Versions

laf  https://hub.docker.com/layers/lafyun/laf/latest/images/sha256-cc131ea5b86eb4fa780a6d196d6eb6f211a4a2fb7518a043915584b48477a2cf?context=explore

### What happened

新建项目，无法进入 

### How to reproduce

安装完毕就这样了，看了prisma-client客户端文档，里面有简单讲解
https://www.prisma.io/docs/concepts/components/prisma-client/crud

### Debug logs

`[Nest] 1  - 02/07/2023, 8:17:37 AM     LOG [ApplicationTaskService] Application qfqsxx updated to phase created
[Nest] 1  - 02/07/2023, 8:17:37 AM     LOG [ApplicationTaskService] Application qfqsxx updated to phase created
[Nest] 1  - 02/07/2023, 8:17:37 AM   ERROR [ApplicationTaskService] Error: 
Invalid `this.prisma.storageUser.create()` invocation in
/app/dist/storage/storage.service.js:41:52

  38     this.logger.error(r1.error);
  39     return false;
  40 }
→ 41 const user = await this.prisma.storageUser.create(
The change you are trying to make would violate the required relation 'ApplicationToStorageUser' between the `Application` and `StorageUser` models.
[Nest] 1  - 02/07/2023, 8:17:37 AM   DEBUG [ApplicationAuthGuard] check auth of: appid: qfqsxx, user: 63e204d90aa2dd4c11ddf413
[Nest] 1  - 02/07/2023, 8:17:37 AM   ERROR [ApplicationTaskService] Error: 
Invalid `this.prisma.storageUser.create()` invocation in
/app/dist/storage/storage.service.js:41:52

  38     this.logger.error(r1.error);
  39     return false;
  40 }
→ 41 const user = await this.prisma.storageUser.create(
The change you are trying to make would violate the required relation 'ApplicationToStorageUser' between the `Application` and `StorageUser` models.
[Nest] 1  - 02/07/2023, 8:17:37 AM   ERROR [ExceptionsHandler] The request signature we calculated does not match the signature you provided. Check your key and signing method.
SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
    at throwDefaultError (/app/node_modules/@aws-sdk/client-sts/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22)
    at deserializeAws_queryAssumeRoleCommandError (/app/node_modules/@aws-sdk/client-sts/dist-cjs/protocols/Aws_query.js:148:51)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/node_modules/@aws-sdk/client-sts/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /app/node_modules/@aws-sdk/client-sts/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:14:20
    at async /app/node_modules/@aws-sdk/client-sts/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at async /app/node_modules/@aws-sdk/client-sts/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:5:22
    at async StorageService.getOssSTS (/app/dist/storage/storage.service.js:90:16)
    at async ApplicationController.findOne (/app/dist/application/application.controller.js:65:25)
    at async /app/node_modules/@nestjs/core/router/router-execution-context.js:46:28
`

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
Thanks to the feedback, it has been found to be a bug and will be fixed in the next release.
