### ISSUE TITLE
[Bug] database Name‘s length tips error

### ISSUE THREAD

**Issue by nightwhite** [labring/laf#753]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

lafyun.com

### CPU Architecture

amd64

### Versions

v1.0.0-beta.1

### What happened

Create a new database name,When there is only one letter as name, the prompt is wrong

![image](https://user-images.githubusercontent.com/22722256/217437444-6282e03a-2911-460e-86cb-ad740f49a93b.png)

### How to reproduce

Create a new database name,When there is only one letter as name, the prompt is wrong

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
fixed.
