### ISSUE TITLE
[Feature] On-line export function input and output parameter type definition

### ISSUE THREAD

**Issue by SOVLOOKUP** [labring/laf#755]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

能够在线导出函数的出入参类型定义，然后在sdk中使用，达到像trpc一样的编码体验

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
Good advice. Do you have a more specific description.
