### ISSUE TITLE
[Bug] The timed task of the cloud function trigger is invalid

### ISSUE THREAD

**Issue by nightwhite** [labring/laf#760]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

lafyun.com

### CPU Architecture

amd64

### Versions

预览版

### What happened

<img width="205" alt="image" src="https://user-images.githubusercontent.com/22722256/217722265-94029889-62ca-4cd6-831a-b9cc115ae6ba.png">
一次不会执行

### How to reproduce

设置了定时任务一次都不会执行

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
Known issues will be fixed in the next release.
