### ISSUE TITLE
[Feature] Support cloud storage batch delete and directory delete

### ISSUE THREAD

**Issue by sulnong** [labring/laf#768]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

Delete more than one file or a directory is a common demmand in cloud storage,
laf 1.0 web have not supported yet.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
Directory deletion supported in current version.
