### ISSUE TITLE
[Feature] Show the object storage AK/SK

### ISSUE THREAD

**Issue by fanux** [labring/laf#771]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

So I can use s3 CLI to put some file in command line

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
Duplicated with https://github.com/labring/laf/issues/890
