### ISSUE TITLE
[Feature] Using HPA as application runtime

### ISSUE THREAD

**Issue by fanux** [labring/laf#772]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

So the pod will autoscale. It can save a lot of resources. Users only need to configure the replica number range and scaling strategy, such as CPU ratio.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zsnmwy** [comment]
How about supporting [Crane EHPA](http://gocrane.io/docs/tutorials/using-effective-hpa-to-scaling-with-effectiveness/) to autoscale base on TimeSeries?
We can get a reliable number of replicas from the crane.

**Comment by maslow** [comment]
HPA supported.
