### ISSUE TITLE
文档目录建议

### ISSUE THREAD

**Issue by fanux** [labring/laf#79]
* 概览
* 部署 (推荐直接使用laf云，部署就是sealos run ....)
* 快速开始
* 使用教程
    * 云函数 (创建，编写，发布，删除)
    * 云数据库
    * 对象存储
    * 静态网页托管
* 示例介绍
    * 三分钟使用开发并上线一个注册/登录应用
    * 开发一个短信通知服务
    * 开发一个微信群通知应用
    * 微信/支付宝支付功能
    * 与区块链对接功能
    * 实现一个拨测功能检测网站健康状态
    * 使用关系型数据库
    * 使用websocket长连接
    * 使用github action静态网页托管
* 原理介绍
    * 架构介绍
* API 
* 使用案例
    *  使用laf开发xxx小程序
    *  使用laf开发区块链Dapp

**Comment by maslow** [comment]
(WIP)Document Repo: https://github.com/lafjs/laf-docs
