### ISSUE TITLE
[Question] 在www.lafyun.com网站注册后，收到反诈骗中心的电话，说网站被确认从事诈骗怎么回事？

### ISSUE THREAD

**Issue by zhihuiyin** [labring/laf#808]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Question

在www.lafyun.com网站注册后，收到反诈骗中心的电话，说网站被确认从事诈骗怎么回事？

**Comment by maslow** [comment]
这个是什么情况，怎么说的，是点名说这个网站有问题？

**Comment by maslow** [comment]
这个是国内合法备案的网站，如果认定网站有问题，应该先找我了，不是境外网站。
