### ISSUE TITLE
[Question] cloud db add VS mongo insertOne/insertMany

### ISSUE THREAD

**Issue by LennyHsu** [labring/laf#809]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Question

目前使用的是v0.8:
现象：
    使用cloud.mongo 进行事务操作，发现之前用cloud.db.add() 添加了数据 , 用cloud.mongo.findOne({ _id: new Object('xxx')}) ， 查询为null ,  cloud.mongo.findOne({ _id: 'xxx'})， 则能查到。
    使用cloud.mongo.insertOne() 添加的数据可以使用 cloud.mongo.findOne({ _id: new Object('xxx')})  查询到。

理论上cloud.db.add() 的数据应该也是ObjectId 的吧 ？目前出了这个现象， 正在查是不是add的_id数据类型与原生insertOne不一致造成的，如果是，就只能换成原生crud方式了

这是我从db服务器中同一collection中分别用 insertOne() 和 cloud add 进行添加的数据
<img width="610" alt="image" src="https://user-images.githubusercontent.com/39997507/220327467-b1e75e81-bc77-481e-b922-d2a94bda527b.png">

**Comment by syrm-ll** [comment]
> 理论上cloud.db.add() 的数据应该也是ObjectId 的吧 ？

在以前, 为了避免 ObjectId 和 string 类型的ID带来的混乱, 曾经统一使用 string 类型ID, 具体细节不清楚, 应该是在 database-proxy 里做的;
现在不清楚, 仅供参考

> 如果是，就只能换成原生crud方式了

如果这么做, JS-SDK 那边有风险, 很可能查询不到数据

**Comment by LennyHsu** [comment]
> 

是的，因为用到了事务之前代码写完了就是查不到数据， 目前我已经全部换成 Mongo client 调用了
