### ISSUE TITLE
[bug] Dependency load error after custom port

### ISSUE THREAD

**Issue by jveay** [labring/laf#812]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

Linux (self-host)

### What happened

Dependency load error after custom port
![image](https://user-images.githubusercontent.com/21017524/220630263-790fd9b9-5417-4256-b165-f349ed8caf35.png)

### How to reproduce

1.修改laf/deploy/build/charts/apisix/values.yaml
servicePort: 24444
containerPort: 24444

2.修改/laf/deploy/build 下的start.sh
MINIO_EXTERNAL_ENDPOINT="${HTTP_SCHEMA}://${MINIO_DOMAIN}:24444"
CASDOOR_ENDPOINT="${HTTP_SCHEMA}://${CASDOOR_HOST}:24444"
CASDOOR_REDIRECT_URI="${HTTP_SCHEMA}://${DOMAIN}:24444/login_callback"
helm install server -n ${NAMESPACE} \
    --set databaseUrl=${DATABASE_URL} \
    --set jwt.secret=${SERVER_JWT_SECRET} \
    --set apiServerHost=api.${DOMAIN} \
    --set apiServerUrl=${HTTP_SCHEMA}://api.${DOMAIN}:24444 \
    --set casdoor.endpoint=${CASDOOR_ENDPOINT} \
    --set casdoor.client_id=${CASDOOR_CLIENT_ID} \
    --set casdoor.client_secret=${CASDOOR_CLIENT_SECRET} \
    --set casdoor.redirect_uri=${CASDOOR_REDIRECT_URI} \
    --set default_region.minio_domain=${MINIO_DOMAIN} \
    --set default_region.minio_external_endpoint=${MINIO_EXTERNAL_ENDPOINT} \
    --set default_region.minio_internal_endpoint=${MINIO_INTERNAL_ENDPOINT} \
    --set default_region.minio_root_access_key=${MINIO_ROOT_ACCESS_KEY} \
    --set default_region.minio_root_secret_key=${MINIO_ROOT_SECRET_KEY} \
    --set default_region.runtime_domain=${DOMAIN}:24444 \
    --set default_region.website_domain=site.${DOMAIN}:24444 \
    --set default_region.tls=false \
    --set default_region.apisix_api_url=${APISIX_API_URL} \
    --set default_region.apisix_api_key=${APISIX_API_KEY} \
    --set default_region.apisix_public_port=24444 \

3.执行start.sh 创建应用后云函数无法加载依赖
![image](https://user-images.githubusercontent.com/21017524/220630263-790fd9b9-5417-4256-b165-f349ed8caf35.png)

4.laf-server 日志
![image](https://user-images.githubusercontent.com/21017524/220631533-7d476cf0-d444-4c60-ad63-d35c5f98180f.png)

5.进入apisix-dashboard 删除端口后恢复正常
![image](https://user-images.githubusercontent.com/21017524/220631954-52f95e85-7e30-40ec-8175-4b00cd1f77aa.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
<img width="460" alt="image" src="https://user-images.githubusercontent.com/7122237/220705950-4b0dde60-44cb-4132-8ad0-198c3f77c260.png">

了解了，首先上图这两个 domain 是不能加端口号的。

然后，前端应该把网关的端口写到 url 中去  @LeezQ  @zuoFeng59556 @kongwy229

**Comment by LeezQ** [comment]
fixed
