### ISSUE TITLE
[bug] 2 error

### ISSUE THREAD

**Issue by nightwhite** [labring/laf#814]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

preview.laf.run

### What happened

![image](https://user-images.githubusercontent.com/22722256/220804605-ba1a2b37-7ed5-487c-bc82-0514f042748d.png)
![image](https://user-images.githubusercontent.com/22722256/220804683-1a662fcf-3f4e-45fe-85da-4cd9a7f664ba.png)

### How to reproduce

1.如图所示,去调试接口,服务器崩了
2.cloud.invoke($name,{
      ...ctx
    })
    写法提示报错,实际没错

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
fixed.
