### ISSUE TITLE
[bug] function return Internal Server Error

### ISSUE THREAD

**Issue by nightwhite** [labring/laf#816]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

preview.laf.run

### What happened

![image](https://user-images.githubusercontent.com/22722256/220892435-de6d87df-544d-4fee-af6f-fed55f18b804.png)

### How to reproduce

code:

import cloud from '@lafjs/cloud'

export async function main(ctx: FunctionContext) {
  console.log('Hello World')
  var funcname = "$$admin_Agetlist"
  var funcnum = funcname.match(/\$/g)?funcname.match(/\$/g).length:0
  console.log(funcnum)
  return funcnum
}

一旦用浏览器访问一下该函数,该函数后续就会Internal Server Error ,并且后面就算改成
export async function main(ctx: FunctionContext) {
  return 1
}
还是Internal Server Error 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
ref: https://stackoverflow.com/questions/39498601/unable-to-send-numbers-using-res-send-using-express-with-node

Express has this problem, which will be fixed in laf in the next release.

**Comment by maslow** [comment]
fixed in https://github.com/labring/laf/pull/817
