### ISSUE TITLE
[bug] laf-cli  uploading file to storage Error

### ISSUE THREAD

**Issue by juukee** [labring/laf#824]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

preview.laf.run

### What happened

![1677307305832](https://user-images.githubusercontent.com/28680837/221342856-75c59fc6-406b-43b1-a3f2-91034a50a31a.png)

### How to reproduce

NO 1 :   Cannot upload the entire folder to storage
NO 2 :     `index.html` Cannot be the default index document

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
NO 1: This is a bug on windows path ?  @skyoct   
NO 2: Bucket do not support default index document. And `html` content type will be forbidden in future.  Use website hosting to host a bucket as a site, that support default index.html.
