### ISSUE TITLE
[bug] cannot remove storage directory

### ISSUE THREAD

**Issue by skyoct** [labring/laf#830]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

preview.laf.run

### What happened

The web storage cannot delete the folder because the delete button is not found

### How to reproduce

1. upload a file in a secondary directory

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
ref: https://github.com/minio/minio/issues/16756
