### ISSUE TITLE
[Feature] cli invoke function support parameters

### ISSUE THREAD

**Issue by skyoct** [labring/laf#842]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

cli invoke function support parameters

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by genie88** [comment]
Usage: main func exec [options] <funcName>

exec function

Options:
  -l --log <count>                   print log
  -X --method <method>               request method, eg -X HEAD/GET/POST/PUT/DELETE
  -H --header <request headers>      request headers, eg -H '{"Content-Type": "application/json"}'
  -q --query <request query params>  request query params, eg -q "key1=val1&key2=val2"
  -d --data <request body data>      request body data, eg -d '{"key1": "val1"}'
  -r --requestId                     print requestId (default: false)
  -h, --help                         display help for command
