### ISSUE TITLE
[Feature] Support mongoDB conditional query command to better search documents in the collection view page

### ISSUE THREAD

**Issue by genie88** [labring/laf#880]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

Currently only support find by id operation, it need support basic mongoDB conditional query command to better search documents in the collection view page

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by nightwhite** [comment]
支持的,cloud.mongo  就是原生的 mongo driver，可以执行 mongo 的所有能力，直接按 mongo 官方文档使用就好了。

**Comment by genie88** [comment]
> 支持的,cloud.mongo 就是原生的 mongo driver，可以执行 mongo 的所有能力，直接按 mongo 官方文档使用就好了。
I want to add an user friendly interface in this page for a better UX
<img width="1193" alt="image" src="https://user-images.githubusercontent.com/12219371/224605180-2334f87c-a330-45e7-be43-fb0275cf519f.png">
