### ISSUE TITLE
[bug] laf.dev Unable to register.

### ISSUE THREAD

**Issue by cdredfox** [labring/laf#888]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

laf.dev

### What happened

I encountered an error **电话false %s** when registering on laf.dev, but I used a valid mobile phone number that starts with 159 as required.

### How to reproduce

1. Go to the website https://login.laf.dev/signup/laf.
2. Fill in the registration form with the required information, including your mobile phone number that starts with "159".
3. Click on the "Register" button to submit your registration request.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by LeezQ** [comment]
Try again, we previously used Casdoor, now replaced with our own service.
