### ISSUE TITLE
[Feature] Bucket supports gzip and brotli

### ISSUE THREAD

**Issue by juukee** [labring/laf#889]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

The public cloud bucket cannot be customized to nginx. I hope it can support gzip and brotli to speed up website access

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
got.

**Comment by maslow** [comment]
done.
