### ISSUE TITLE
[bug] Error name validation in OSS

### ISSUE THREAD

**Issue by Penggeor** [labring/laf#903]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

preview.laf.run

### What happened

I am using the name "db" to create a new OSS but can't pass the rule:

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/68799055/225311654-52b4315b-a5d1-40c2-b8c3-80decfb6e71b.png">

### How to reproduce

See the picture above.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by LeezQ** [comment]
#950
