### ISSUE TITLE
[bug] Newly built cloud storage space cannot set the capacity

### ISSUE THREAD

**Issue by nightwhite** [labring/laf#916]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

laf.dev

### What happened

![image](https://user-images.githubusercontent.com/22722256/225681629-b2743a17-7f43-4b90-b2ce-bbdae2e26560.png)

### How to reproduce

Newly built cloud storage space cannot set the capacity

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by LeezQ** [comment]
All buckets use the same storage space, no longer distinguish the capacity of each bucket

**Comment by nightwhite** [comment]
Then calculate their total capacity?
