### ISSUE TITLE
[bug] dark mode style problem

### ISSUE THREAD

**Issue by nightwhite** [labring/laf#918]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

laf.dev

### What happened

![image](https://user-images.githubusercontent.com/22722256/225683928-5dc406f1-901f-4358-957d-7d2235230f33.png)
![image](https://user-images.githubusercontent.com/22722256/225684733-7c02da6a-4fc5-4599-bd93-13c2985d9d83.png)
![image](https://user-images.githubusercontent.com/22722256/225684828-28dc8ca6-85a2-4477-a241-55e7dca20361.png)

### How to reproduce

In the dark mode, after exiting the login, the style problem will appear again

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by LeezQ** [comment]
#919
