### ISSUE TITLE
[bug] 无法打开 laf.dev

### ISSUE THREAD

**Issue by laterdayi** [labring/laf#920]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

preview.laf.run

### What happened

无法打开 laf.dev

### How to reproduce

无法打开 laf.dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by skyoct** [comment]
底层机器原因，已恢复

**Comment by feZsy** [comment]
大佬，你好，laf.dev访问不了，我想续费弄不了
![image](https://github.com/labring/laf/assets/27257365/d66d67f5-e10c-48dd-9136-723c2679bad2)

**Comment by LsyWeb** [comment]
> 大佬，你好，laf.dev访问不了，我想继续收费弄不了 ![图像](https://user-images.githubusercontent.com/27257365/239789513-d66d67f5-e10c-48dd-9136-723c2679bad2.png)

https://aircode.io/dashboard 铁铁，可以试一下这个云开发平台，目前也是免费

**Comment by maslow** [comment]
> 大佬，你好，laf.dev访问不了，我想续费弄不了 ![image](https://user-images.githubusercontent.com/27257365/239789513-d66d67f5-e10c-48dd-9136-723c2679bad2.png)

我测试了一下是可以访问的， 或可尝试刷新一下浏览器，清除缓存？
另外，由于 https://laf.dev 是海外节点，有小部分大陆地区 网络访问不稳定的情况。
可考虑使用 国内版 https://laf.run

**Comment by feZsy** [comment]
> > 大佬，你好，laf.dev访问不了，我想续费弄不了 ![image](https://user-images.githubusercontent.com/27257365/239789513-d66d67f5-e10c-48dd-9136-723c2679bad2.png)
> 
> 我测试了一下是可以访问的， 或可尝试刷新一下浏览器，清除缓存？ 另外，由于 https://laf.dev 是海外节点，有小部分大陆地区 网络访问不稳定的情况。 可考虑使用 国内版 https://laf.run

我用梯子访问还是有问题，用国内版本无法用openai，可以帮忙看下有解决方案吗？
<img width="830" alt="image" src="https://github.com/labring/laf/assets/27257365/87bbe37f-811c-4b99-8989-647e884b71a3">

**Comment by feZsy** [comment]
> > > 大佬，你好，laf.dev访问不了，我想续费弄不了 ![image](https://user-images.githubusercontent.com/27257365/239789513-d66d67f5-e10c-48dd-9136-723c2679bad2.png)
> > 
> > 
> > 我测试了一下是可以访问的， 或可尝试刷新一下浏览器，清除缓存？ 另外，由于 https://laf.dev 是海外节点，有小部分大陆地区 网络访问不稳定的情况。 可考虑使用 国内版 https://laf.run
> 
> 我用梯子访问还是有问题，用国内版本无法用openai，可以帮忙看下有解决方案吗？ <img alt="image" width="830" src="https://user-images.githubusercontent.com/27257365/243605742-87bbe37f-811c-4b99-8989-647e884b71a3.png">

https://github.com/labring/laf/issues/1044#issuecomment-1513288913
