### ISSUE TITLE
[Feature] import and export application

### ISSUE THREAD

**Issue by juukee** [labring/laf#923]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

I hope to add applications that can be imported and exported to facilitate overall application migration

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
You can use `laf-cli`  pull and push applications.
