### ISSUE TITLE
[bug] ctx.request error

### ISSUE THREAD

**Issue by nightwhite** [labring/laf#928]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

laf.dev

### What happened

![image](https://user-images.githubusercontent.com/22722256/226176153-60afd3d4-41f9-42b1-bd7e-0ae44944766b.png)

### How to reproduce

ctx.request 
This way of writing errors,but actually right

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by yuedanlabs** [comment]
According to latest code: [types.ts](https://github.com/labring/laf/blob/main/runtimes/nodejs/src/support/function-engine/types.ts#L48)

```
export interface FunctionContext {
  ...
  request?: Request
  ...
```

so... `ctx.request` can be use here. It's totally right.

Maybe you should use the latest `laf.dev` to avoid this issue.

<img width="486" alt="image" src="https://user-images.githubusercontent.com/95392548/228713369-82c444a7-8c36-40c0-9c60-91d88c5e00af.png">


BTW: all props you can use in this ctx is:
```
files
headers
query
body
params
auth: (has deprecated in the latest version, and should use user instead)
user
requestId
method
socket
request
response
__function_name
```
