### ISSUE TITLE
[bug] cloud.invoke ctx errors

### ISSUE THREAD

**Issue by nightwhite** [labring/laf#929]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

laf.dev

### What happened

![image](https://user-images.githubusercontent.com/22722256/226176357-cdca90fb-3057-43b8-b627-d9226b23f421.png)

### How to reproduce

cloud.invoke("naem",{...ctx})
This way of writing errors,but actually right

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by yuedanlabs** [comment]
#928 same as this.

Maybe you should use the latest `laf.dev` to avoid this issue

<img width="480" alt="image" src="https://user-images.githubusercontent.com/95392548/228715113-3d07a4ff-454b-446a-96c7-d43ed2cd64ff.png">

**Comment by nightwhite** [comment]
OK
