### ISSUE TITLE
[Question] lafyun.com loads very slowly, is the old version out of service?

### ISSUE THREAD

**Issue by amzqing** [labring/laf#932]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Question

I can't open console.lafyun.com, and it took me a long time to load it. Even if I opened it, NPM failed to load.

**Comment by amzqing** [comment]
How to migrate the old version to laf.dev? laf.dev can only choose the Hong Kong region, when will it provide mainland China?

**Comment by maslow** [comment]
1. We will soon release a migration guide document.
2. laf.dev will provide a region for mainland China this month.

**Comment by maslow** [comment]
The issue of slow access for old versions has been resolved. The reason was that the resources were overloaded.

**Comment by amzqing** [comment]
> The issue of slow access for old versions has been resolved. The reason was that the resources were overloaded.

Ok, thanks for your reply.
