### ISSUE TITLE
[Feature] A single application can differentiate between production and development environments.

### ISSUE THREAD

**Issue by amzqing** [labring/laf#939]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

Seeing that laf.dev adopts a single application charging scheme, it is a bit wasteful to purchase an application separately for the development environment.

If only one free application is used as the development environment, resources are not enough to develop multiple projects at the same time.

If developers are allowed to deploy the entire privatized environment on local computers, the development process will become very troublesome again, which will lose the biggest advantage of serverless.

I hope that the designers of laf can fully integrate a better development experience process into laf from the perspective of actually using laf to develop projects, from development, testing, to online operation and maintenance. Instead of simply developing laf from the perspective of developing laf.

I am more than happy to pay for Laf's application resources, but it is very uncomfortable for me to purchase a complete application resource for each new project's development environment.

- Hope to be able to distinguish the development or online environment within a single application.
- Hope to be able to invite project team members to collaborate and develop like version 0.8.
- It is hoped that the entire development process can be completed on the web side instead of switching to the local. If you want to switch to local, you hope to quickly and lightweight integrate the local development environment instead of deploying a complete privatized version of laf.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
Thank you for your valuable suggestions. We are currently researching and investigating some of the issues you mentioned and plan to implement some of them in Q2.

Let me discuss your suggestions with the product team and provide a more specific response afterwards.
