### ISSUE TITLE
[bug] The https://laf.dev has collapsed again?

### ISSUE THREAD

**Issue by njuptlzf** [labring/laf#942]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

preview.laf.run

### What happened

The [official website](https://laf.dev) has collapsed again?

Are there plans to achieve high availability? Or notify users in a prominent location before updating?

### How to reproduce

open https://laf.dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
Sorry, our servers underwent a cross-region data center migration last night, which resulted in the unavailability of our service for a period of time. We have now completed the migration and you should be able to access our service normally. Thank you for your patience and understanding.
