### ISSUE TITLE
[bug] Real-name authentication is not possible

### ISSUE THREAD

**Issue by PerttyZhan** [labring/laf#946]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

Mac (self-host)

### What happened

I found that the real name authentication interface on the official website reported 400 errors。
<img width="612" alt="image" src="https://user-images.githubusercontent.com/10022074/226784102-ba2302c6-10dd-4a06-8667-f41ec0c2fbd1.png">
<img width="520" alt="image" src="https://user-images.githubusercontent.com/10022074/226784195-adfc5e42-04ce-4ef0-b109-dd44bbf2fb64.png">

### How to reproduce

website: https://console.lafyun.com/#/id-verify
Fill in information

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by LeezQ** [comment]
Please use our new stable site https://laf.dev,  lafyun.com will shut down
