### ISSUE TITLE
[bug] cli  Forbidden resource!

### ISSUE THREAD

**Issue by juukee** [labring/laf#962]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

preview.laf.run

### What happened

```
$ laf func list
Forbidden resource!
```

### How to reproduce

1. laf login
2. ```$ laf func list
Forbidden resource!```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by skyoct** [comment]
@juukee Please confirm if the appId belongs to you or not.

**Comment by juukee** [comment]
> 

yes

**Comment by juukee** [comment]
> try this https://forum.laf.run/d/67

i want to know the reason and how to fix it?

**Comment by nightwhite** [comment]
> > try this https://forum.laf.run/d/67
> 
> i want to know the reason and how to fix it?

Whether this vscode plugin is used normally？

**Comment by juukee** [comment]
laf-cli ：1.0.0-beta.5
node： v16.19.1
system： Windows 10 企业版 LTSC
![1680172562116](https://user-images.githubusercontent.com/28680837/228810423-f87cf5f9-ff4a-45ec-b80f-084c553cfc49.png)

**Comment by maslow** [comment]
Got.
Try running laf app list to check if it works properly.

Reference: https://github.com/labring/laf/blob/main/docs/guide/cli/index.md

**Comment by maslow** [comment]
Based on my understanding of the documentation, you should first run the laf app init command to initialize or select an application. After that, you can view the list of cloud functions for that application.

**Comment by juukee** [comment]
it because it not init first,but the warning information is not clear 
```
laf app init 
```
