### ISSUE TITLE
[Question] laf.dev page blank

### ISSUE THREAD

**Issue by zhuyajing001** [labring/laf#966]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Question

recently，when i open the site https://laf.dev/，I can just see the page blank。there is nothing，just the blank page。I do not know what is wrong。before， I upload one index.html,  this site is also blank page。when i run the local program ，everything is OK。

**Comment by kaikaibenkai** [comment]
Did you enable JavaScript? Or you're using IE

**Comment by zhuyajing001** [comment]
I used safari and Google Chrome and Microsoft Edge，all the same blank。but one week a ago，I came in the site [https://laf.dev/](https://laf.dev) normally。so，I think is the site changed something make wrong ？ I dont konw。

**Comment by kaikaibenkai** [comment]
Press F12 to see details.

**Comment by zhuyajing001** [comment]
<img width="1298" alt="截屏2023-03-26 18 17 56" src="https://user-images.githubusercontent.com/11852926/227769367-5b33917d-3740-4351-bd60-20f7c436e025.png">

**Comment by maslow** [comment]
Due to the current laf.dev server being located in Singapore, domestic China Mobile users are experiencing issues with the network connection to Alibaba Cloud Singapore. We have contacted Alibaba Cloud for assistance in resolving this issue.

**Comment by nightwhite** [comment]
Domestic nodes are online this Friday

**Comment by nightwhite** [comment]
https://laf.run
