### ISSUE TITLE
[bug] HTTP 500 when return a `Object` within `BigInt`

### ISSUE THREAD

**Issue by kaikaibenkai** [labring/laf#967]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

preview.laf.run

### What happened

```ts
export async function main() {
  return { value: BigInt(100) }; // ES2020
}
```

Response: `Internal Service Error`

### How to reproduce

See `What happened`

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by kaikaibenkai** [comment]
`JSON.stringify` doesn't support `BigInt` at this time....

**Comment by nightwhite** [comment]
return { data: BigInt(100).toString() };

**Comment by kaikaibenkai** [comment]
> return { data: BigInt(100).toString() };

Thanks. Now I'm using this method.
