### ISSUE TITLE
[Feature] Sync some future ideas from forum

### ISSUE THREAD

**Issue by aFlyBird0** [labring/laf#968]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

Sync from forum.laf.run 

(Written in Chinese)

Apps based on Laf:

* [Exploring the Applications of Laf: Adding Read Count Statistics and Other Features to Blogs.](https://forum.laf.run/d/154)
* [Exploring the Applications of Laf: Blog Comment System.](https://forum.laf.run/d/163)

Laf itself(roadmap):

* [Exploring the Development Direction of Laf: Integration with Git/SVN and other Code Version Control Tools/Platforms.](https://forum.laf.run/d/166)
* [Exploring the Development Direction of Laf: Enhancing Configurability / Configuration as Code](https://forum.laf.run/d/169)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by nightwhite** [comment]
6
