### ISSUE TITLE
laf-cli

### ISSUE THREAD

**Issue by spadeACE7** [labring/laf#969]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

Mac (self-host)

### What happened

Use the laf-cli command line tool

After installation, execute any command report：

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'node:fs'
Require stack:

### How to reproduce

https://www.lafyun.com/guide/cli/

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by skyoct** [comment]
@spadeACE7 
1. Please indicate in the title what the issue is for
2. Please explain how you plan to repair it？

**Comment by spadeACE7** [comment]
> I think it might be an issue with the version of Node.js. What version are you using?

Thank you for reminding me. I updated the node version and it can be used normally

**Comment by spadeACE7** [comment]
> @spadeACE7
> 
> 1. Please indicate in the title what the issue is for
> 2. Please explain how you plan to repair it？

The node version issue has been resolved. thank you
