### ISSUE TITLE
laf-client-sdk

### ISSUE THREAD

**Issue by spadeACE7** [labring/laf#973]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

Mac (self-host)

### What happened

Downloaded and installed laf-client-sdk, used in the code, the page appeared a bug as follows：
![image](https://user-images.githubusercontent.com/82570883/228127102-e23bc70f-5bd0-4a05-b127-14830ae7a24b.png)

Looking at the laf-client-sdk dependency, I wonder if the version of axios is too low. Af-client-sdk relies on axios version 0.21.1; The latest axios is 1.3.4.

### How to reproduce

1. Install laf-client-sdk in the project

2. Use laf-client-sdk according to the document

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by yuedanlabs** [comment]
may be you can try `http` instead of `https` in `baseUrl `, the use of `https` for node axios has some problems.

e.g.

```
const cloud = new Cloud({
  // the laf app server base url
  // baseUrl: "https://APPID.lafyun.com",
  baseUrl: "http://APPID.lafyun.com",
  ...
});
```
