### ISSUE TITLE
[Bug] tsl version,cant connet mssql

### ISSUE THREAD

**Issue by juukee** [labring/laf#975]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

```
Unable to connect to the database: ConnectionError: Failed to connect to 127.0.0.1:1433 - 78BBA006F67F0000:error:0A000102:SSL routines:ssl_choose_client_version:unsupported protocol
```
When I connect to SQL SERVER, an error is reported, and the tsl version is inconsistent, resulting in inability to connect
How to fix it ?

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by juukee** [comment]
@maslow how to fix it ?

**Comment by maslow** [comment]
It seems a mssql issue, not laf scope
