### ISSUE TITLE
[Feature]  Function list display Total Functions

### ISSUE THREAD

**Issue by sunnycat1991** [labring/laf#982]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

函数列表展示函数总数
Function list display Total Functions 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by maslow** [comment]
Good suggestion  @LeezQ

**Comment by LeezQ** [comment]
already released
