### ISSUE TITLE
[bug] can not upload to storage with multiple files or folders

### ISSUE THREAD

**Issue by yuedanlabs** [labring/laf#984]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

preview.laf.run

### What happened

can not upload to laf.dev storage with multiple files or folders.

the folders: 

```
test
├── api
│   ├── test-02.md
│   └── test.md
├── examples
│   └── test.html
├── hi.html
└── readme.md
```
 
and this is the result and console.log

<img width="1347" alt="image" src="https://user-images.githubusercontent.com/95392548/228805866-9fd16654-12d3-49e8-82b3-5e1f50ff528c.png">

- a single file can uploaded
- multiple files without folders can uploaded, but not so sure(because some times failed)
- folder and multiple folders can not be uploaded
- files with folders can not be uploaded

### How to reproduce

open new tab with laf.dev

 and select an app storage to upload.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by LeezQ** [comment]
now you can upload files and folder together , in your case,
1st: create a folder named 'test'
2nd: chose 'upload folder' , then select your 'test' folder
